#!/usr/bin/perl
use strict;
use warnings;
use utf8;
use JSON::PP;
use Encode qw(encode_utf8);
use File::Spec;

binmode STDOUT, ':raw';

my $query = lc(join(' ', @ARGV) // '');
$query =~ s/^\s+|\s+$//g;

# Load custom keywords from config file
my $config_dir = File::Spec->catdir($ENV{HOME}, '.config', 'semoji');
my $config_file = File::Spec->catfile($config_dir, 'custom.json');
my $settings_file = File::Spec->catfile($config_dir, 'settings.json');
my %custom_keywords;
my %settings = (unicode_enabled => 0);

if (-f $config_file) {
    if (open my $fh, '<:utf8', $config_file) {
        local $/;
        my $json_text = <$fh>;
        close $fh;
        eval {
            my $data = decode_json(encode_utf8($json_text));
            %custom_keywords = %$data if ref($data) eq 'HASH';
        };
    }
}

if (-f $settings_file) {
    if (open my $fh, '<:utf8', $settings_file) {
        local $/;
        my $json_text = <$fh>;
        close $fh;
        eval {
            my $data = decode_json(encode_utf8($json_text));
            %settings = (%settings, %$data) if ref($data) eq 'HASH';
        };
    }
}

my @emojis = (
    # Smileys & Emotion
    ['😀', 'Grinning Face', ['happy', 'smile', 'joy', 'cheerful', 'glad', 'pleased', 'delighted']],
    ['😃', 'Grinning Face with Big Eyes', ['happy', 'smile', 'joy', 'excited', 'eager']],
    ['😄', 'Grinning Face with Smiling Eyes', ['happy', 'smile', 'joy', 'laugh', 'pleased']],
    ['😁', 'Beaming Face', ['happy', 'smile', 'grin', 'excited', 'cheerful']],
    ['😅', 'Grinning Face with Sweat', ['nervous', 'awkward', 'relief', 'phew', 'sweat']],
    ['😂', 'Face with Tears of Joy', ['laugh', 'funny', 'hilarious', 'lol', 'lmao', 'crying laughing', 'haha']],
    ['🤣', 'Rolling on the Floor Laughing', ['laugh', 'funny', 'hilarious', 'rofl', 'lmao']],
    ['😊', 'Smiling Face with Smiling Eyes', ['happy', 'blush', 'pleased', 'content', 'warm']],
    ['😇', 'Smiling Face with Halo', ['angel', 'innocent', 'blessed', 'holy', 'good']],
    ['🙂', 'Slightly Smiling Face', ['okay', 'fine', 'subtle', 'mild', 'pleasant']],
    ['🙃', 'Upside-Down Face', ['sarcasm', 'silly', 'irony', 'goofy', 'playful']],
    ['😉', 'Winking Face', ['wink', 'flirt', 'joke', 'playful', 'hint']],
    ['😌', 'Relieved Face', ['relieved', 'peaceful', 'calm', 'content', 'relaxed']],
    ['😍', 'Smiling Face with Heart-Eyes', ['love', 'crush', 'adore', 'infatuation', 'heart eyes']],
    ['🥰', 'Smiling Face with Hearts', ['love', 'affection', 'adore', 'grateful', 'blessed']],
    ['😘', 'Face Blowing a Kiss', ['kiss', 'love', 'flirt', 'romantic', 'mwah']],
    ['😗', 'Kissing Face', ['kiss', 'whistle', 'smooch']],
    ['😙', 'Kissing Face with Smiling Eyes', ['kiss', 'affection', 'happy kiss']],
    ['😚', 'Kissing Face with Closed Eyes', ['kiss', 'love', 'affection', 'peck']],
    ['😋', 'Face Savoring Food', ['yummy', 'delicious', 'tasty', 'food', 'hungry']],
    ['😛', 'Face with Tongue', ['tongue', 'playful', 'silly', 'tease', 'bleh']],
    ['😜', 'Winking Face with Tongue', ['tongue', 'wink', 'playful', 'silly', 'crazy']],
    ['🤪', 'Zany Face', ['crazy', 'wild', 'goofy', 'silly', 'wacky']],
    ['😝', 'Squinting Face with Tongue', ['tongue', 'playful', 'silly', 'gross', 'eww']],
    ['🤑', 'Money-Mouth Face', ['money', 'rich', 'dollar', 'wealth', 'greedy', 'cash']],
    ['🤗', 'Hugging Face', ['hug', 'embrace', 'warm', 'friendly', 'welcoming']],
    ['🤭', 'Face with Hand Over Mouth', ['oops', 'giggle', 'shy', 'secret', 'tee-hee']],
    ['🤫', 'Shushing Face', ['quiet', 'shush', 'secret', 'silence', 'hush']],
    ['🤔', 'Thinking Face', ['think', 'hmm', 'wonder', 'consider', 'ponder', 'curious']],
    ['🤐', 'Zipper-Mouth Face', ['secret', 'quiet', 'mute', 'lips sealed', 'confidential']],
    ['🤨', 'Face with Raised Eyebrow', ['skeptical', 'suspicious', 'doubt', 'really', 'hmm']],
    ['😐', 'Neutral Face', ['neutral', 'meh', 'indifferent', 'blank', 'expressionless']],
    ['😑', 'Expressionless Face', ['blank', 'meh', 'unimpressed', 'deadpan']],
    ['😶', 'Face Without Mouth', ['speechless', 'silent', 'mute', 'no comment']],
    ['😏', 'Smirking Face', ['smirk', 'smug', 'flirt', 'suggestive', 'sly']],
    ['😒', 'Unamused Face', ['unamused', 'annoyed', 'bored', 'meh', 'whatever']],
    ['🙄', 'Face with Rolling Eyes', ['eye roll', 'annoyed', 'frustrated', 'whatever', 'duh']],
    ['😬', 'Grimacing Face', ['awkward', 'nervous', 'tense', 'cringe', 'yikes']],
    ['😮‍💨', 'Face Exhaling', ['sigh', 'relief', 'exhale', 'tired', 'phew']],
    ['🤥', 'Lying Face', ['lie', 'pinocchio', 'dishonest', 'fib']],
    ['😔', 'Pensive Face', ['sad', 'pensive', 'disappointed', 'reflective']],
    ['😪', 'Sleepy Face', ['sleepy', 'tired', 'drowsy', 'exhausted']],
    ['🤤', 'Drooling Face', ['drool', 'hungry', 'desire', 'want', 'yummy']],
    ['😴', 'Sleeping Face', ['sleep', 'tired', 'zzz', 'nap', 'rest', 'snore']],
    ['😷', 'Face with Medical Mask', ['sick', 'mask', 'ill', 'covid', 'medical', 'health']],
    ['🤒', 'Face with Thermometer', ['sick', 'fever', 'ill', 'temperature', 'unwell']],
    ['🤕', 'Face with Head-Bandage', ['hurt', 'injured', 'bandage', 'pain', 'accident']],
    ['🤢', 'Nauseated Face', ['sick', 'nausea', 'gross', 'disgusted', 'queasy', 'vomit']],
    ['🤮', 'Face Vomiting', ['vomit', 'sick', 'puke', 'gross', 'disgusting']],
    ['🤧', 'Sneezing Face', ['sneeze', 'sick', 'cold', 'allergies', 'achoo']],
    ['🥵', 'Hot Face', ['hot', 'heat', 'sweating', 'warm', 'temperature']],
    ['🥶', 'Cold Face', ['cold', 'freezing', 'frozen', 'ice', 'chilly']],
    ['🥴', 'Woozy Face', ['drunk', 'dizzy', 'woozy', 'tipsy', 'intoxicated']],
    ['😵', 'Face with Crossed-Out Eyes', ['dizzy', 'dead', 'shocked', 'overwhelmed']],
    ['😵‍💫', 'Face with Spiral Eyes', ['dizzy', 'hypnotized', 'disoriented', 'confused']],
    ['🤯', 'Exploding Head', ['mind blown', 'shocked', 'amazed', 'wow', 'unbelievable']],
    ['🤠', 'Cowboy Hat Face', ['cowboy', 'western', 'yeehaw', 'country', 'hat']],
    ['🥳', 'Partying Face', ['party', 'celebrate', 'birthday', 'fun', 'festive', 'congratulations']],
    ['🥸', 'Disguised Face', ['disguise', 'incognito', 'hidden', 'spy', 'glasses']],
    ['😎', 'Smiling Face with Sunglasses', ['cool', 'sunglasses', 'awesome', 'confident', 'chill']],
    ['🤓', 'Nerd Face', ['nerd', 'geek', 'smart', 'glasses', 'studious']],
    ['🧐', 'Face with Monocle', ['fancy', 'curious', 'investigate', 'inspect', 'hmm']],
    ['😕', 'Confused Face', ['confused', 'puzzled', 'unsure', 'uncertain']],
    ['😟', 'Worried Face', ['worried', 'concerned', 'anxious', 'nervous']],
    ['🙁', 'Slightly Frowning Face', ['sad', 'frown', 'disappointed', 'unhappy']],
    ['☹️', 'Frowning Face', ['sad', 'frown', 'unhappy', 'disappointed']],
    ['😮', 'Face with Open Mouth', ['surprised', 'wow', 'shocked', 'amazed']],
    ['😯', 'Hushed Face', ['surprised', 'stunned', 'speechless', 'wow']],
    ['😲', 'Astonished Face', ['astonished', 'shocked', 'amazed', 'wow', 'omg']],
    ['😳', 'Flushed Face', ['embarrassed', 'flushed', 'shy', 'awkward', 'blush']],
    ['🥺', 'Pleading Face', ['please', 'puppy eyes', 'beg', 'cute', 'sad', 'uwu']],
    ['😦', 'Frowning Face with Open Mouth', ['sad', 'shocked', 'disappointed']],
    ['😧', 'Anguished Face', ['anguish', 'shocked', 'horrified', 'distressed']],
    ['😨', 'Fearful Face', ['fear', 'scared', 'afraid', 'terrified', 'shock']],
    ['😰', 'Anxious Face with Sweat', ['anxious', 'nervous', 'worried', 'stressed', 'sweat']],
    ['😥', 'Sad but Relieved Face', ['sad', 'relieved', 'disappointed', 'sweat']],
    ['😢', 'Crying Face', ['cry', 'sad', 'tear', 'unhappy', 'upset']],
    ['😭', 'Loudly Crying Face', ['cry', 'sobbing', 'sad', 'tears', 'bawling', 'wailing']],
    ['😱', 'Face Screaming in Fear', ['scream', 'fear', 'horror', 'shocked', 'scared', 'omg']],
    ['😖', 'Confounded Face', ['frustrated', 'confused', 'upset', 'stressed']],
    ['😣', 'Persevering Face', ['struggle', 'frustrated', 'trying', 'effort']],
    ['😞', 'Disappointed Face', ['disappointed', 'sad', 'let down', 'unhappy']],
    ['😓', 'Downcast Face with Sweat', ['disappointed', 'sad', 'sweat', 'hard work']],
    ['😩', 'Weary Face', ['tired', 'weary', 'frustrated', 'exhausted', 'fed up']],
    ['😫', 'Tired Face', ['tired', 'exhausted', 'frustrated', 'sleepy']],
    ['🥱', 'Yawning Face', ['yawn', 'tired', 'sleepy', 'bored', 'boring']],
    ['😤', 'Face with Steam From Nose', ['angry', 'frustrated', 'triumph', 'huffing']],
    ['😡', 'Pouting Face', ['angry', 'mad', 'furious', 'rage', 'pout']],
    ['😠', 'Angry Face', ['angry', 'mad', 'annoyed', 'grumpy']],
    ['🤬', 'Face with Symbols on Mouth', ['swear', 'curse', 'angry', 'censored', 'expletive']],
    ['😈', 'Smiling Face with Horns', ['devil', 'evil', 'mischief', 'naughty', 'trouble']],
    ['👿', 'Angry Face with Horns', ['devil', 'angry', 'evil', 'imp']],
    ['💀', 'Skull', ['dead', 'death', 'skeleton', 'scary', 'halloween', 'rip']],
    ['☠️', 'Skull and Crossbones', ['death', 'danger', 'poison', 'pirate', 'toxic']],
    ['💩', 'Pile of Poo', ['poop', 'crap', 'shit', 'funny', 'gross']],
    ['🤡', 'Clown Face', ['clown', 'fool', 'circus', 'funny', 'joke']],
    ['👹', 'Ogre', ['monster', 'scary', 'japanese', 'oni', 'demon']],
    ['👺', 'Goblin', ['monster', 'japanese', 'tengu', 'demon']],
    ['👻', 'Ghost', ['ghost', 'halloween', 'spooky', 'scary', 'boo']],
    ['👽', 'Alien', ['alien', 'ufo', 'space', 'extraterrestrial', 'et']],
    ['👾', 'Alien Monster', ['alien', 'game', 'space invaders', 'pixel', 'arcade']],
    ['🤖', 'Robot', ['robot', 'bot', 'machine', 'ai', 'android', 'technology']],
    ['😺', 'Smiling Cat', ['cat', 'happy', 'smile', 'pet']],
    ['😸', 'Grinning Cat', ['cat', 'happy', 'grin', 'pet']],
    ['😹', 'Cat with Tears of Joy', ['cat', 'laugh', 'funny', 'pet']],
    ['😻', 'Smiling Cat with Heart-Eyes', ['cat', 'love', 'heart eyes', 'pet']],
    ['😼', 'Cat with Wry Smile', ['cat', 'smirk', 'sly', 'pet']],
    ['😽', 'Kissing Cat', ['cat', 'kiss', 'love', 'pet']],
    ['🙀', 'Weary Cat', ['cat', 'shocked', 'scared', 'pet']],
    ['😿', 'Crying Cat', ['cat', 'sad', 'cry', 'pet']],
    ['😾', 'Pouting Cat', ['cat', 'angry', 'grumpy', 'pet']],
    ['🙈', 'See-No-Evil Monkey', ['monkey', 'hide', 'shy', 'embarrassed', "don't look"]],
    ['🙉', 'Hear-No-Evil Monkey', ['monkey', 'ignore', 'not listening', 'la la la']],
    ['🙊', 'Speak-No-Evil Monkey', ['monkey', 'secret', 'oops', 'quiet', 'shh']],

    # Gestures & Body Parts
    ['👋', 'Waving Hand', ['wave', 'hello', 'hi', 'bye', 'goodbye', 'greeting']],
    ['🤚', 'Raised Back of Hand', ['hand', 'stop', 'high five']],
    ['🖐️', 'Hand with Fingers Splayed', ['hand', 'five', 'stop', 'high five']],
    ['✋', 'Raised Hand', ['hand', 'stop', 'high five', 'halt']],
    ['🖖', 'Vulcan Salute', ['spock', 'star trek', 'live long', 'prosper']],
    ['👌', 'OK Hand', ['ok', 'okay', 'perfect', 'good', 'nice', 'fine']],
    ['🤌', 'Pinched Fingers', ['italian', 'perfection', 'chef kiss', 'what do you want']],
    ['🤏', 'Pinching Hand', ['small', 'tiny', 'little', 'pinch', 'bit']],
    ['✌️', 'Victory Hand', ['peace', 'victory', 'two', 'v sign']],
    ['🤞', 'Crossed Fingers', ['luck', 'hope', 'fingers crossed', 'wish']],
    ['🤟', 'Love-You Gesture', ['love', 'ily', 'rock', 'sign language']],
    ['🤘', 'Sign of the Horns', ['rock', 'metal', 'horns', 'rock on', 'party']],
    ['🤙', 'Call Me Hand', ['call', 'shaka', 'hang loose', 'phone', 'surf']],
    ['👈', 'Backhand Index Pointing Left', ['point', 'left', 'direction', 'that way']],
    ['👉', 'Backhand Index Pointing Right', ['point', 'right', 'direction', 'this way']],
    ['👆', 'Backhand Index Pointing Up', ['point', 'up', 'direction', 'above']],
    ['🖕', 'Middle Finger', ['middle finger', 'fuck', 'flip off', 'rude', 'angry']],
    ['👇', 'Backhand Index Pointing Down', ['point', 'down', 'direction', 'below']],
    ['☝️', 'Index Pointing Up', ['point', 'up', 'one', 'wait', 'important']],
    ['👍', 'Thumbs Up', ['good', 'yes', 'ok', 'approve', 'like', 'agree', 'nice']],
    ['👎', 'Thumbs Down', ['bad', 'no', 'dislike', 'disapprove', 'disagree', 'boo']],
    ['✊', 'Raised Fist', ['fist', 'power', 'solidarity', 'punch', 'strong']],
    ['👊', 'Oncoming Fist', ['fist bump', 'punch', 'bro', 'power']],
    ['🤛', 'Left-Facing Fist', ['fist bump', 'punch', 'left']],
    ['🤜', 'Right-Facing Fist', ['fist bump', 'punch', 'right']],
    ['👏', 'Clapping Hands', ['clap', 'applause', 'bravo', 'congratulations', 'well done']],
    ['🙌', 'Raising Hands', ['celebrate', 'praise', 'hooray', 'yay', 'hallelujah']],
    ['👐', 'Open Hands', ['open', 'hands', 'hug', 'jazz hands']],
    ['🤲', 'Palms Up Together', ['prayer', 'please', 'give', 'receive']],
    ['🤝', 'Handshake', ['handshake', 'deal', 'agreement', 'meeting', 'partnership']],
    ['🙏', 'Folded Hands', ['pray', 'please', 'thank you', 'hope', 'namaste', 'grateful']],
    ['✍️', 'Writing Hand', ['write', 'writing', 'sign', 'signature']],
    ['💅', 'Nail Polish', ['nails', 'beauty', 'fabulous', 'sassy', 'glamour']],
    ['🤳', 'Selfie', ['selfie', 'photo', 'camera', 'phone', 'picture']],
    ['💪', 'Flexed Biceps', ['strong', 'muscle', 'power', 'strength', 'gym', 'workout', 'flex']],
    ['🦾', 'Mechanical Arm', ['robot', 'prosthetic', 'strong', 'cyborg']],
    ['🦿', 'Mechanical Leg', ['robot', 'prosthetic', 'cyborg']],
    ['🦵', 'Leg', ['leg', 'kick', 'limb']],
    ['🦶', 'Foot', ['foot', 'kick', 'stomp']],
    ['👂', 'Ear', ['ear', 'hear', 'listen', 'sound']],
    ['🦻', 'Ear with Hearing Aid', ['deaf', 'hearing aid', 'accessibility']],
    ['👃', 'Nose', ['nose', 'smell', 'sniff']],
    ['🧠', 'Brain', ['brain', 'smart', 'think', 'intelligence', 'mind']],
    ['👀', 'Eyes', ['eyes', 'look', 'see', 'watch', 'stare', 'looking']],
    ['👁️', 'Eye', ['eye', 'see', 'look', 'watch']],
    ['👅', 'Tongue', ['tongue', 'taste', 'lick']],
    ['👄', 'Mouth', ['mouth', 'lips', 'kiss']],

    # Hearts & Love
    ['💋', 'Kiss Mark', ['kiss', 'lips', 'love', 'lipstick', 'smooch']],
    ['❤️', 'Red Heart', ['love', 'heart', 'romance', 'like', 'favorite']],
    ['🧡', 'Orange Heart', ['love', 'heart', 'orange', 'friendship']],
    ['💛', 'Yellow Heart', ['love', 'heart', 'yellow', 'friendship', 'happiness']],
    ['💚', 'Green Heart', ['love', 'heart', 'green', 'nature', 'jealousy']],
    ['💙', 'Blue Heart', ['love', 'heart', 'blue', 'trust', 'loyalty']],
    ['💜', 'Purple Heart', ['love', 'heart', 'purple', 'sensitive', 'bts']],
    ['🖤', 'Black Heart', ['love', 'heart', 'black', 'dark', 'emo', 'goth']],
    ['🤍', 'White Heart', ['love', 'heart', 'white', 'pure', 'clean']],
    ['🤎', 'Brown Heart', ['love', 'heart', 'brown', 'nature']],
    ['💔', 'Broken Heart', ['heartbreak', 'sad', 'breakup', 'hurt', 'pain']],
    ['❤️‍🔥', 'Heart on Fire', ['love', 'passion', 'lust', 'burning', 'desire']],
    ['❤️‍🩹', 'Mending Heart', ['healing', 'recovery', 'getting better', 'health']],
    ['❣️', 'Heart Exclamation', ['love', 'heart', 'exclamation', 'emphasis']],
    ['💕', 'Two Hearts', ['love', 'hearts', 'romance', 'couple']],
    ['💞', 'Revolving Hearts', ['love', 'hearts', 'romance', 'falling in love']],
    ['💓', 'Beating Heart', ['love', 'heartbeat', 'alive', 'excited']],
    ['💗', 'Growing Heart', ['love', 'heart', 'growing', 'affection']],
    ['💖', 'Sparkling Heart', ['love', 'heart', 'sparkle', 'excited', 'shiny']],
    ['💘', 'Heart with Arrow', ['love', 'cupid', 'romance', 'valentine']],
    ['💝', 'Heart with Ribbon', ['love', 'gift', 'present', 'valentine']],
    ['💟', 'Heart Decoration', ['love', 'heart', 'decoration']],

    # Celebrations & Objects
    ['🎉', 'Party Popper', ['party', 'celebrate', 'congratulations', 'birthday', 'new year', 'confetti']],
    ['🎊', 'Confetti Ball', ['party', 'celebrate', 'confetti', 'festive']],
    ['🎈', 'Balloon', ['party', 'balloon', 'birthday', 'celebration']],
    ['🎁', 'Wrapped Gift', ['gift', 'present', 'birthday', 'christmas', 'surprise']],
    ['🎂', 'Birthday Cake', ['birthday', 'cake', 'celebration', 'party']],
    ['🎄', 'Christmas Tree', ['christmas', 'tree', 'holiday', 'xmas', 'december']],
    ['🎃', 'Jack-O-Lantern', ['halloween', 'pumpkin', 'spooky', 'october']],
    ['🎆', 'Fireworks', ['fireworks', 'celebration', 'new year', 'july 4th']],
    ['🎇', 'Sparkler', ['sparkler', 'fireworks', 'celebration']],
    ['✨', 'Sparkles', ['sparkle', 'shine', 'magic', 'special', 'clean', 'new', 'star']],
    ['🎀', 'Ribbon', ['ribbon', 'gift', 'present', 'bow', 'cute']],
    ['🏆', 'Trophy', ['trophy', 'winner', 'award', 'champion', 'first place', 'success']],
    ['🥇', '1st Place Medal', ['gold', 'first', 'winner', 'medal', 'champion']],
    ['🥈', '2nd Place Medal', ['silver', 'second', 'medal', 'runner up']],
    ['🥉', '3rd Place Medal', ['bronze', 'third', 'medal']],
    ['🏅', 'Sports Medal', ['medal', 'sports', 'winner', 'achievement']],
    ['🎖️', 'Military Medal', ['medal', 'military', 'honor', 'award']],

    # Weather & Nature
    ['☀️', 'Sun', ['sun', 'sunny', 'weather', 'hot', 'summer', 'bright']],
    ['🌙', 'Crescent Moon', ['moon', 'night', 'sleep', 'dark', 'crescent']],
    ['⭐', 'Star', ['star', 'favorite', 'rating', 'sky', 'night']],
    ['🌟', 'Glowing Star', ['star', 'glow', 'sparkle', 'shiny', 'special']],
    ['💫', 'Dizzy', ['dizzy', 'star', 'shooting star', 'sparkle']],
    ['🌈', 'Rainbow', ['rainbow', 'colorful', 'pride', 'lgbtq', 'colors']],
    ['☁️', 'Cloud', ['cloud', 'weather', 'sky', 'cloudy']],
    ['⛈️', 'Cloud with Lightning and Rain', ['storm', 'thunder', 'lightning', 'rain', 'weather']],
    ['🌧️', 'Cloud with Rain', ['rain', 'rainy', 'weather', 'cloud']],
    ['❄️', 'Snowflake', ['snow', 'cold', 'winter', 'frozen', 'ice']],
    ['🔥', 'Fire', ['fire', 'hot', 'lit', 'flame', 'burn', 'awesome', 'trending']],
    ['💧', 'Droplet', ['water', 'drop', 'rain', 'tear', 'sweat']],
    ['🌊', 'Water Wave', ['wave', 'ocean', 'sea', 'water', 'surf', 'beach']],

    # Plants
    ['🌸', 'Cherry Blossom', ['flower', 'cherry', 'blossom', 'spring', 'pink', 'japan']],
    ['🌺', 'Hibiscus', ['flower', 'tropical', 'hawaii', 'pink']],
    ['🌻', 'Sunflower', ['flower', 'sunflower', 'yellow', 'summer', 'sun']],
    ['🌹', 'Rose', ['flower', 'rose', 'love', 'romance', 'red', 'valentine']],
    ['🌷', 'Tulip', ['flower', 'tulip', 'spring', 'pink']],
    ['🌱', 'Seedling', ['plant', 'seedling', 'growth', 'new', 'sprout', 'garden']],
    ['🌲', 'Evergreen Tree', ['tree', 'evergreen', 'pine', 'forest', 'nature']],
    ['🌳', 'Deciduous Tree', ['tree', 'nature', 'forest', 'green']],
    ['🌴', 'Palm Tree', ['palm', 'tree', 'tropical', 'beach', 'vacation']],
    ['🌵', 'Cactus', ['cactus', 'desert', 'plant', 'succulent']],
    ['🍀', 'Four Leaf Clover', ['clover', 'luck', 'lucky', 'irish', 'st patrick']],
    ['🍁', 'Maple Leaf', ['maple', 'leaf', 'fall', 'autumn', 'canada']],
    ['🍂', 'Fallen Leaf', ['leaf', 'fall', 'autumn', 'nature']],
    ['🍃', 'Leaf Fluttering in Wind', ['leaf', 'wind', 'nature', 'green']],

    # Animals
    ['🐶', 'Dog Face', ['dog', 'puppy', 'pet', 'cute', 'animal']],
    ['🐱', 'Cat Face', ['cat', 'kitty', 'pet', 'cute', 'animal', 'meow']],
    ['🐭', 'Mouse Face', ['mouse', 'animal', 'cute', 'rodent']],
    ['🐹', 'Hamster', ['hamster', 'pet', 'cute', 'rodent']],
    ['🐰', 'Rabbit Face', ['rabbit', 'bunny', 'pet', 'cute', 'easter']],
    ['🦊', 'Fox', ['fox', 'animal', 'clever', 'cute']],
    ['🐻', 'Bear', ['bear', 'animal', 'cute', 'teddy']],
    ['🐼', 'Panda', ['panda', 'bear', 'animal', 'cute', 'china']],
    ['🐨', 'Koala', ['koala', 'animal', 'cute', 'australia']],
    ['🐯', 'Tiger Face', ['tiger', 'animal', 'cat', 'wild']],
    ['🦁', 'Lion', ['lion', 'animal', 'king', 'wild', 'cat']],
    ['🐮', 'Cow Face', ['cow', 'animal', 'farm', 'moo']],
    ['🐷', 'Pig Face', ['pig', 'animal', 'farm', 'oink']],
    ['🐸', 'Frog', ['frog', 'animal', 'amphibian', 'pepe']],
    ['🐵', 'Monkey Face', ['monkey', 'animal', 'ape', 'primate']],
    ['🐔', 'Chicken', ['chicken', 'animal', 'bird', 'farm']],
    ['🐧', 'Penguin', ['penguin', 'animal', 'bird', 'cold', 'linux']],
    ['🐦', 'Bird', ['bird', 'animal', 'fly', 'tweet']],
    ['🦅', 'Eagle', ['eagle', 'bird', 'america', 'freedom']],
    ['🦆', 'Duck', ['duck', 'bird', 'animal', 'quack']],
    ['🦉', 'Owl', ['owl', 'bird', 'wise', 'night']],
    ['🐺', 'Wolf', ['wolf', 'animal', 'wild', 'howl']],
    ['🐗', 'Boar', ['boar', 'pig', 'wild', 'animal']],
    ['🐴', 'Horse Face', ['horse', 'animal', 'pony']],
    ['🦄', 'Unicorn', ['unicorn', 'magic', 'fantasy', 'mythical', 'horse']],
    ['🐝', 'Bee', ['bee', 'insect', 'honey', 'buzz']],
    ['🐛', 'Bug', ['bug', 'insect', 'caterpillar']],
    ['🦋', 'Butterfly', ['butterfly', 'insect', 'pretty', 'nature']],
    ['🐌', 'Snail', ['snail', 'slow', 'animal']],
    ['🐙', 'Octopus', ['octopus', 'sea', 'ocean', 'tentacles']],
    ['🦀', 'Crab', ['crab', 'sea', 'ocean', 'zodiac', 'cancer']],
    ['🐠', 'Tropical Fish', ['fish', 'tropical', 'ocean', 'sea']],
    ['🐟', 'Fish', ['fish', 'ocean', 'sea', 'animal']],
    ['🐬', 'Dolphin', ['dolphin', 'ocean', 'sea', 'smart', 'flipper']],
    ['🐳', 'Spouting Whale', ['whale', 'ocean', 'sea', 'big']],
    ['🦈', 'Shark', ['shark', 'ocean', 'dangerous', 'jaws']],
    ['🐊', 'Crocodile', ['crocodile', 'alligator', 'reptile']],
    ['🐢', 'Turtle', ['turtle', 'slow', 'reptile', 'shell']],
    ['🦎', 'Lizard', ['lizard', 'reptile', 'gecko']],
    ['🐍', 'Snake', ['snake', 'reptile', 'slither']],
    ['🦖', 'T-Rex', ['dinosaur', 't-rex', 'jurassic', 'extinct']],
    ['🦕', 'Sauropod', ['dinosaur', 'long neck', 'jurassic', 'extinct']],

    # Food & Drink
    ['🍎', 'Red Apple', ['apple', 'fruit', 'healthy', 'red', 'teacher']],
    ['🍊', 'Tangerine', ['orange', 'fruit', 'citrus']],
    ['🍋', 'Lemon', ['lemon', 'fruit', 'citrus', 'sour', 'yellow']],
    ['🍌', 'Banana', ['banana', 'fruit', 'yellow']],
    ['🍉', 'Watermelon', ['watermelon', 'fruit', 'summer']],
    ['🍇', 'Grapes', ['grapes', 'fruit', 'wine', 'purple']],
    ['🍓', 'Strawberry', ['strawberry', 'fruit', 'berry', 'red']],
    ['🍑', 'Peach', ['peach', 'fruit', 'butt', 'booty']],
    ['🍒', 'Cherries', ['cherry', 'cherries', 'fruit', 'red']],
    ['🥑', 'Avocado', ['avocado', 'fruit', 'guacamole', 'healthy', 'millennial']],
    ['🥕', 'Carrot', ['carrot', 'vegetable', 'orange', 'healthy']],
    ['🌽', 'Ear of Corn', ['corn', 'vegetable', 'cob']],
    ['🌶️', 'Hot Pepper', ['pepper', 'hot', 'spicy', 'chili']],
    ['🥒', 'Cucumber', ['cucumber', 'vegetable', 'pickle']],
    ['🥬', 'Leafy Green', ['lettuce', 'salad', 'vegetable', 'healthy', 'green']],
    ['🥦', 'Broccoli', ['broccoli', 'vegetable', 'healthy', 'green']],
    ['🍄', 'Mushroom', ['mushroom', 'fungus', 'toadstool']],
    ['🥜', 'Peanuts', ['peanut', 'nut', 'legume']],
    ['🍞', 'Bread', ['bread', 'toast', 'loaf', 'carbs']],
    ['🥐', 'Croissant', ['croissant', 'bread', 'french', 'pastry']],
    ['🥖', 'Baguette Bread', ['baguette', 'bread', 'french']],
    ['🧀', 'Cheese Wedge', ['cheese', 'dairy', 'cheddar']],
    ['🍳', 'Cooking', ['egg', 'cooking', 'breakfast', 'fried']],
    ['🥞', 'Pancakes', ['pancakes', 'breakfast', 'syrup']],
    ['🥓', 'Bacon', ['bacon', 'meat', 'breakfast', 'pork']],
    ['🍔', 'Hamburger', ['burger', 'hamburger', 'fast food', 'beef']],
    ['🍟', 'French Fries', ['fries', 'french fries', 'fast food', 'potato']],
    ['🍕', 'Pizza', ['pizza', 'italian', 'fast food', 'slice']],
    ['🌭', 'Hot Dog', ['hot dog', 'sausage', 'fast food']],
    ['🥪', 'Sandwich', ['sandwich', 'lunch', 'bread']],
    ['🌮', 'Taco', ['taco', 'mexican', 'food', 'tuesday']],
    ['🌯', 'Burrito', ['burrito', 'mexican', 'wrap']],
    ['🍜', 'Steaming Bowl', ['noodles', 'ramen', 'soup', 'asian', 'pho']],
    ['🍝', 'Spaghetti', ['spaghetti', 'pasta', 'italian', 'noodles']],
    ['🍣', 'Sushi', ['sushi', 'japanese', 'fish', 'rice']],
    ['🍤', 'Fried Shrimp', ['shrimp', 'tempura', 'seafood']],
    ['🍦', 'Soft Ice Cream', ['ice cream', 'dessert', 'sweet', 'cone']],
    ['🍩', 'Doughnut', ['donut', 'doughnut', 'dessert', 'sweet']],
    ['🍪', 'Cookie', ['cookie', 'dessert', 'sweet', 'biscuit']],
    ['🍰', 'Shortcake', ['cake', 'dessert', 'strawberry', 'sweet']],
    ['🧁', 'Cupcake', ['cupcake', 'dessert', 'sweet', 'muffin']],
    ['🍫', 'Chocolate Bar', ['chocolate', 'candy', 'sweet', 'dessert']],
    ['🍬', 'Candy', ['candy', 'sweet', 'sugar']],
    ['🍭', 'Lollipop', ['lollipop', 'candy', 'sweet']],
    ['☕', 'Hot Beverage', ['coffee', 'tea', 'hot', 'drink', 'cafe', 'morning']],
    ['🍵', 'Teacup', ['tea', 'green tea', 'hot', 'drink', 'japanese']],
    ['🍺', 'Beer Mug', ['beer', 'drink', 'alcohol', 'cheers']],
    ['🍻', 'Clinking Beer Mugs', ['beer', 'cheers', 'drink', 'alcohol', 'toast']],
    ['🥂', 'Clinking Glasses', ['champagne', 'cheers', 'toast', 'celebration', 'wine']],
    ['🍷', 'Wine Glass', ['wine', 'drink', 'alcohol', 'red wine']],
    ['🍸', 'Cocktail Glass', ['cocktail', 'martini', 'drink', 'alcohol']],
    ['🍹', 'Tropical Drink', ['cocktail', 'tropical', 'drink', 'vacation']],
    ['🧃', 'Beverage Box', ['juice', 'juice box', 'drink']],
    ['🧋', 'Bubble Tea', ['boba', 'bubble tea', 'drink', 'taiwanese']],

    # Activities & Sports
    ['⚽', 'Soccer Ball', ['soccer', 'football', 'ball', 'sport']],
    ['🏀', 'Basketball', ['basketball', 'ball', 'sport', 'nba']],
    ['🏈', 'American Football', ['football', 'american', 'sport', 'nfl']],
    ['⚾', 'Baseball', ['baseball', 'ball', 'sport', 'mlb']],
    ['🎾', 'Tennis', ['tennis', 'ball', 'sport', 'racket']],
    ['🏐', 'Volleyball', ['volleyball', 'ball', 'sport', 'beach']],
    ['🏉', 'Rugby Football', ['rugby', 'ball', 'sport']],
    ['🎱', 'Pool 8 Ball', ['pool', 'billiards', '8 ball', 'game']],
    ['🏓', 'Ping Pong', ['ping pong', 'table tennis', 'sport']],
    ['🏸', 'Badminton', ['badminton', 'shuttlecock', 'sport']],
    ['🥊', 'Boxing Glove', ['boxing', 'fight', 'sport', 'punch']],
    ['🥋', 'Martial Arts Uniform', ['martial arts', 'karate', 'judo', 'taekwondo']],
    ['⛳', 'Flag in Hole', ['golf', 'sport', 'hole']],
    ['⛷️', 'Skier', ['ski', 'skiing', 'winter', 'sport', 'snow']],
    ['🏂', 'Snowboarder', ['snowboard', 'winter', 'sport', 'snow']],
    ['🏄', 'Person Surfing', ['surf', 'surfing', 'beach', 'wave', 'ocean']],
    ['🏊', 'Person Swimming', ['swim', 'swimming', 'pool', 'water']],
    ['🚴', 'Person Biking', ['bike', 'bicycle', 'cycling', 'sport']],
    ['🧘', 'Person in Lotus Position', ['yoga', 'meditation', 'zen', 'mindfulness', 'calm']],
    ['🎮', 'Video Game', ['game', 'gaming', 'video game', 'controller', 'play']],
    ['🕹️', 'Joystick', ['game', 'arcade', 'joystick', 'retro']],
    ['🎲', 'Game Die', ['dice', 'game', 'random', 'chance', 'gambling']],
    ['🧩', 'Puzzle Piece', ['puzzle', 'game', 'piece', 'jigsaw']],
    ['♟️', 'Chess Pawn', ['chess', 'game', 'strategy', 'pawn']],
    ['🎯', 'Direct Hit', ['target', 'bullseye', 'goal', 'aim', 'dart']],
    ['🎳', 'Bowling', ['bowling', 'sport', 'pins', 'ball']],
    ['🎰', 'Slot Machine', ['slot', 'casino', 'gambling', 'jackpot']],

    # Travel & Places
    ['🚗', 'Automobile', ['car', 'vehicle', 'drive', 'road', 'auto']],
    ['🚕', 'Taxi', ['taxi', 'cab', 'car', 'uber', 'lyft']],
    ['🚌', 'Bus', ['bus', 'vehicle', 'public transport', 'school']],
    ['🚎', 'Trolleybus', ['trolley', 'bus', 'tram', 'transport']],
    ['🏎️', 'Racing Car', ['race car', 'fast', 'formula 1', 'speed']],
    ['🚓', 'Police Car', ['police', 'cop', 'car', 'emergency']],
    ['🚑', 'Ambulance', ['ambulance', 'emergency', 'hospital', 'medical']],
    ['🚒', 'Fire Engine', ['fire truck', 'fire', 'emergency', 'firefighter']],
    ['🚲', 'Bicycle', ['bike', 'bicycle', 'cycling', 'pedal']],
    ['🛵', 'Motor Scooter', ['scooter', 'moped', 'vespa']],
    ['🏍️', 'Motorcycle', ['motorcycle', 'bike', 'harley']],
    ['✈️', 'Airplane', ['plane', 'airplane', 'flight', 'travel', 'fly']],
    ['🚀', 'Rocket', ['rocket', 'space', 'launch', 'fast', 'startup']],
    ['🛸', 'Flying Saucer', ['ufo', 'alien', 'space', 'flying saucer']],
    ['🚁', 'Helicopter', ['helicopter', 'chopper', 'fly']],
    ['🛶', 'Canoe', ['canoe', 'kayak', 'boat', 'paddle']],
    ['⛵', 'Sailboat', ['sailboat', 'boat', 'sailing', 'yacht']],
    ['🚢', 'Ship', ['ship', 'boat', 'cruise', 'ocean']],
    ['🚂', 'Locomotive', ['train', 'locomotive', 'steam', 'railroad']],
    ['🚆', 'Train', ['train', 'rail', 'transport']],
    ['🚇', 'Metro', ['metro', 'subway', 'underground', 'train']],
    ['🏠', 'House', ['house', 'home', 'building', 'residence']],
    ['🏡', 'House with Garden', ['house', 'home', 'garden', 'yard']],
    ['🏢', 'Office Building', ['office', 'building', 'work', 'business']],
    ['🏣', 'Japanese Post Office', ['post office', 'mail', 'japan']],
    ['🏥', 'Hospital', ['hospital', 'medical', 'health', 'doctor']],
    ['🏦', 'Bank', ['bank', 'money', 'finance', 'building']],
    ['🏨', 'Hotel', ['hotel', 'travel', 'accommodation', 'vacation']],
    ['🏪', 'Convenience Store', ['store', 'shop', 'convenience', '7-eleven']],
    ['🏫', 'School', ['school', 'education', 'building', 'learn']],
    ['🏛️', 'Classical Building', ['museum', 'government', 'classical', 'building']],
    ['⛪', 'Church', ['church', 'religion', 'christian', 'building']],
    ['🕌', 'Mosque', ['mosque', 'muslim', 'islam', 'religion']],
    ['🕍', 'Synagogue', ['synagogue', 'jewish', 'judaism', 'religion']],
    ['🗽', 'Statue of Liberty', ['statue of liberty', 'new york', 'america', 'freedom']],
    ['🗼', 'Tokyo Tower', ['tokyo tower', 'japan', 'landmark']],
    ['🗾', 'Map of Japan', ['japan', 'map', 'country']],
    ['🌍', 'Globe Europe-Africa', ['earth', 'globe', 'world', 'europe', 'africa']],
    ['🌎', 'Globe Americas', ['earth', 'globe', 'world', 'america', 'americas']],
    ['🌏', 'Globe Asia-Australia', ['earth', 'globe', 'world', 'asia', 'australia']],

    # Tech & Objects
    ['💻', 'Laptop', ['laptop', 'computer', 'work', 'coding', 'programming']],
    ['🖥️', 'Desktop Computer', ['desktop', 'computer', 'pc', 'monitor']],
    ['🖨️', 'Printer', ['printer', 'print', 'paper', 'office']],
    ['⌨️', 'Keyboard', ['keyboard', 'type', 'computer', 'input']],
    ['🖱️', 'Computer Mouse', ['mouse', 'computer', 'click', 'cursor']],
    ['💾', 'Floppy Disk', ['floppy', 'disk', 'save', 'retro', 'storage']],
    ['💿', 'Optical Disk', ['cd', 'dvd', 'disk', 'disc', 'music']],
    ['📱', 'Mobile Phone', ['phone', 'mobile', 'smartphone', 'iphone', 'android', 'cell']],
    ['☎️', 'Telephone', ['phone', 'telephone', 'call', 'retro']],
    ['📞', 'Telephone Receiver', ['phone', 'call', 'receiver']],
    ['📺', 'Television', ['tv', 'television', 'screen', 'watch']],
    ['📻', 'Radio', ['radio', 'music', 'broadcast']],
    ['🎙️', 'Studio Microphone', ['microphone', 'podcast', 'recording', 'studio']],
    ['🎚️', 'Level Slider', ['slider', 'volume', 'audio', 'control']],
    ['🎛️', 'Control Knobs', ['knobs', 'control', 'audio', 'mixer']],
    ['🎤', 'Microphone', ['microphone', 'karaoke', 'sing', 'music']],
    ['🎧', 'Headphone', ['headphones', 'music', 'audio', 'listen']],
    ['📷', 'Camera', ['camera', 'photo', 'picture', 'photography']],
    ['📹', 'Video Camera', ['video', 'camera', 'record', 'film']],
    ['🎬', 'Clapper Board', ['movie', 'film', 'action', 'cinema', 'director']],
    ['📡', 'Satellite Antenna', ['satellite', 'antenna', 'signal', 'broadcast']],
    ['🔋', 'Battery', ['battery', 'power', 'energy', 'charge']],
    ['🔌', 'Electric Plug', ['plug', 'electric', 'power', 'outlet']],
    ['💡', 'Light Bulb', ['idea', 'light', 'bulb', 'bright', 'thought', 'innovation']],
    ['🔦', 'Flashlight', ['flashlight', 'light', 'torch', 'dark']],
    ['🔒', 'Locked', ['lock', 'locked', 'security', 'private', 'password']],
    ['🔓', 'Unlocked', ['unlock', 'open', 'security', 'access']],
    ['🔑', 'Key', ['key', 'lock', 'unlock', 'access', 'password']],
    ['🗝️', 'Old Key', ['key', 'old', 'vintage', 'antique']],
    ['🔨', 'Hammer', ['hammer', 'tool', 'build', 'construction']],
    ['🪓', 'Axe', ['axe', 'tool', 'chop', 'wood']],
    ['⛏️', 'Pick', ['pick', 'pickaxe', 'mine', 'minecraft', 'tool']],
    ['🔧', 'Wrench', ['wrench', 'tool', 'fix', 'repair', 'settings']],
    ['🔩', 'Nut and Bolt', ['nut', 'bolt', 'screw', 'hardware']],
    ['⚙️', 'Gear', ['gear', 'settings', 'cog', 'mechanical', 'options']],
    ['🧲', 'Magnet', ['magnet', 'attract', 'magnetic']],
    ['💈', 'Barber Pole', ['barber', 'haircut', 'salon']],
    ['🧪', 'Test Tube', ['test tube', 'science', 'chemistry', 'lab', 'experiment']],
    ['🧫', 'Petri Dish', ['petri dish', 'science', 'biology', 'lab']],
    ['🧬', 'DNA', ['dna', 'genetics', 'science', 'biology', 'helix']],
    ['🔬', 'Microscope', ['microscope', 'science', 'research', 'lab', 'biology']],
    ['🔭', 'Telescope', ['telescope', 'astronomy', 'space', 'stars', 'science']],
    ['💉', 'Syringe', ['syringe', 'needle', 'vaccine', 'injection', 'medical']],
    ['💊', 'Pill', ['pill', 'medicine', 'drug', 'medication', 'pharmacy']],
    ['🩺', 'Stethoscope', ['stethoscope', 'doctor', 'medical', 'health']],
    ['🩹', 'Adhesive Bandage', ['bandage', 'band-aid', 'injury', 'hurt', 'heal']],

    # Symbols
    ['❌', 'Cross Mark', ['no', 'wrong', 'error', 'cancel', 'delete', 'x']],
    ['✅', 'Check Mark Button', ['yes', 'correct', 'done', 'complete', 'success', 'check']],
    ['☑️', 'Check Box with Check', ['check', 'done', 'complete', 'checkbox']],
    ['✔️', 'Check Mark', ['check', 'correct', 'yes', 'done', 'approved']],
    ['❓', 'Question Mark', ['question', 'what', 'help', 'confused']],
    ['❗', 'Exclamation Mark', ['exclamation', 'important', 'warning', 'alert']],
    ['‼️', 'Double Exclamation Mark', ['exclamation', 'important', 'urgent', 'emphasis']],
    ['⁉️', 'Exclamation Question Mark', ['surprise', 'what', 'shocked', 'interrobang']],
    ['💯', 'Hundred Points', ['100', 'perfect', 'score', 'hundred', 'full marks']],
    ['🔴', 'Red Circle', ['red', 'circle', 'dot', 'stop', 'record']],
    ['🟠', 'Orange Circle', ['orange', 'circle', 'dot']],
    ['🟡', 'Yellow Circle', ['yellow', 'circle', 'dot']],
    ['🟢', 'Green Circle', ['green', 'circle', 'dot', 'go', 'online']],
    ['🔵', 'Blue Circle', ['blue', 'circle', 'dot']],
    ['🟣', 'Purple Circle', ['purple', 'circle', 'dot']],
    ['⚫', 'Black Circle', ['black', 'circle', 'dot']],
    ['⚪', 'White Circle', ['white', 'circle', 'dot']],
    ['🔺', 'Red Triangle Pointed Up', ['triangle', 'up', 'red', 'arrow']],
    ['🔻', 'Red Triangle Pointed Down', ['triangle', 'down', 'red', 'arrow']],
    ['🔶', 'Large Orange Diamond', ['orange', 'diamond', 'shape']],
    ['🔷', 'Large Blue Diamond', ['blue', 'diamond', 'shape']],
    ['➕', 'Plus', ['plus', 'add', 'positive', 'more']],
    ['➖', 'Minus', ['minus', 'subtract', 'negative', 'less']],
    ['➗', 'Divide', ['divide', 'division', 'math']],
    ['✖️', 'Multiply', ['multiply', 'times', 'x', 'math']],
    ['♾️', 'Infinity', ['infinity', 'forever', 'endless', 'unlimited']],
    ['💲', 'Heavy Dollar Sign', ['dollar', 'money', 'price', 'cost', 'currency']],
    ['💱', 'Currency Exchange', ['currency', 'exchange', 'money', 'forex']],
    ['©️', 'Copyright', ['copyright', 'legal', 'c']],
    ['®️', 'Registered', ['registered', 'trademark', 'legal', 'r']],
    ['™️', 'Trade Mark', ['trademark', 'tm', 'brand', 'legal']],
    ['🔙', 'Back Arrow', ['back', 'arrow', 'return', 'previous']],
    ['🔚', 'End Arrow', ['end', 'arrow', 'finish']],
    ['🔛', 'On! Arrow', ['on', 'arrow', 'enable']],
    ['🔜', 'Soon Arrow', ['soon', 'arrow', 'coming']],
    ['🔝', 'Top Arrow', ['top', 'arrow', 'up', 'best']],
    ['⬆️', 'Up Arrow', ['up', 'arrow', 'north']],
    ['⬇️', 'Down Arrow', ['down', 'arrow', 'south']],
    ['⬅️', 'Left Arrow', ['left', 'arrow', 'west', 'back']],
    ['➡️', 'Right Arrow', ['right', 'arrow', 'east', 'forward', 'next']],
    ['↗️', 'Up-Right Arrow', ['up right', 'arrow', 'northeast']],
    ['↘️', 'Down-Right Arrow', ['down right', 'arrow', 'southeast']],
    ['↙️', 'Down-Left Arrow', ['down left', 'arrow', 'southwest']],
    ['↖️', 'Up-Left Arrow', ['up left', 'arrow', 'northwest']],
    ['↕️', 'Up-Down Arrow', ['up down', 'arrow', 'vertical']],
    ['↔️', 'Left-Right Arrow', ['left right', 'arrow', 'horizontal']],
    ['🔄', 'Counterclockwise Arrows', ['refresh', 'reload', 'repeat', 'sync', 'update']],
    ['🔃', 'Clockwise Arrows', ['clockwise', 'repeat', 'cycle']],
    ['🔁', 'Repeat Button', ['repeat', 'loop', 'replay']],
    ['🔂', 'Repeat Single Button', ['repeat one', 'loop', 'single']],
    ['▶️', 'Play Button', ['play', 'start', 'video', 'music']],
    ['⏸️', 'Pause Button', ['pause', 'stop', 'wait']],
    ['⏹️', 'Stop Button', ['stop', 'end', 'halt']],
    ['⏺️', 'Record Button', ['record', 'recording', 'red dot']],
    ['⏭️', 'Next Track Button', ['next', 'skip', 'forward']],
    ['⏮️', 'Last Track Button', ['previous', 'back', 'rewind']],
    ['⏩', 'Fast-Forward Button', ['fast forward', 'skip', 'speed']],
    ['⏪', 'Fast Reverse Button', ['rewind', 'back', 'reverse']],
    ['🔀', 'Shuffle Tracks Button', ['shuffle', 'random', 'mix']],
    ['🔊', 'Speaker High Volume', ['volume', 'loud', 'speaker', 'sound']],
    ['🔉', 'Speaker Medium Volume', ['volume', 'medium', 'speaker', 'sound']],
    ['🔈', 'Speaker Low Volume', ['volume', 'low', 'speaker', 'quiet']],
    ['🔇', 'Muted Speaker', ['mute', 'silent', 'no sound', 'quiet']],
    ['🔔', 'Bell', ['bell', 'notification', 'alert', 'ring']],
    ['🔕', 'Bell with Slash', ['mute', 'silent', 'no notification', 'quiet']],
    ['📢', 'Loudspeaker', ['announcement', 'megaphone', 'loud', 'speaker']],
    ['📣', 'Megaphone', ['megaphone', 'cheer', 'announcement', 'loud']],

    # Office & Stationery
    ['📄', 'Page Facing Up', ['document', 'page', 'file', 'paper']],
    ['📃', 'Page with Curl', ['document', 'page', 'paper', 'scroll']],
    ['📝', 'Memo', ['memo', 'note', 'write', 'document', 'edit', 'pencil']],
    ['📁', 'File Folder', ['folder', 'directory', 'file', 'organize']],
    ['📂', 'Open File Folder', ['folder', 'open', 'directory', 'file']],
    ['🗂️', 'Card Index Dividers', ['dividers', 'organize', 'tabs', 'index']],
    ['📅', 'Calendar', ['calendar', 'date', 'schedule', 'event']],
    ['📆', 'Tear-Off Calendar', ['calendar', 'date', 'schedule']],
    ['📇', 'Card Index', ['rolodex', 'contacts', 'index', 'cards']],
    ['📈', 'Chart Increasing', ['chart', 'graph', 'growth', 'up', 'stonks', 'increase', 'profit']],
    ['📉', 'Chart Decreasing', ['chart', 'graph', 'decline', 'down', 'decrease', 'loss']],
    ['📊', 'Bar Chart', ['chart', 'graph', 'statistics', 'data', 'analytics']],
    ['📋', 'Clipboard', ['clipboard', 'paste', 'list', 'tasks']],
    ['📌', 'Pushpin', ['pin', 'pushpin', 'location', 'mark', 'important']],
    ['📍', 'Round Pushpin', ['pin', 'location', 'map', 'marker']],
    ['📎', 'Paperclip', ['paperclip', 'attachment', 'attach', 'clip']],
    ['🖇️', 'Linked Paperclips', ['paperclips', 'linked', 'attachment']],
    ['📏', 'Straight Ruler', ['ruler', 'measure', 'length', 'straight']],
    ['📐', 'Triangular Ruler', ['ruler', 'triangle', 'measure', 'angle']],
    ['✂️', 'Scissors', ['scissors', 'cut', 'trim']],
    ['🗃️', 'Card File Box', ['file', 'box', 'storage', 'archive']],
    ['🗄️', 'File Cabinet', ['cabinet', 'file', 'storage', 'office']],
    ['🗑️', 'Wastebasket', ['trash', 'delete', 'garbage', 'bin', 'waste']],
    ['✏️', 'Pencil', ['pencil', 'write', 'edit', 'draw']],
    ['🖊️', 'Pen', ['pen', 'write', 'sign']],
    ['🖋️', 'Fountain Pen', ['fountain pen', 'write', 'fancy']],
    ['✒️', 'Black Nib', ['pen', 'nib', 'write', 'calligraphy']],
    ['🖌️', 'Paintbrush', ['paintbrush', 'art', 'paint', 'draw']],
    ['🖍️', 'Crayon', ['crayon', 'color', 'draw', 'kids']],
    ['📚', 'Books', ['books', 'read', 'study', 'library', 'education']],
    ['📖', 'Open Book', ['book', 'read', 'open', 'study']],
    ['📕', 'Closed Book', ['book', 'closed', 'red']],
    ['📗', 'Green Book', ['book', 'green']],
    ['📘', 'Blue Book', ['book', 'blue']],
    ['📙', 'Orange Book', ['book', 'orange']],
    ['📓', 'Notebook', ['notebook', 'journal', 'write']],
    ['📔', 'Notebook with Decorative Cover', ['notebook', 'journal', 'diary']],
    ['📒', 'Ledger', ['ledger', 'notebook', 'accounts']],
    ['📰', 'Newspaper', ['newspaper', 'news', 'press', 'media']],
    ['🗞️', 'Rolled-Up Newspaper', ['newspaper', 'news', 'rolled']],
    ['🏷️', 'Label', ['label', 'tag', 'price', 'sale']],
    ['✉️', 'Envelope', ['envelope', 'email', 'mail', 'letter']],
    ['📧', 'E-Mail', ['email', 'mail', 'message', 'inbox']],
    ['📨', 'Incoming Envelope', ['email', 'incoming', 'receive', 'mail']],
    ['📩', 'Envelope with Arrow', ['email', 'send', 'outgoing', 'mail']],
    ['📤', 'Outbox Tray', ['outbox', 'send', 'upload', 'mail']],
    ['📥', 'Inbox Tray', ['inbox', 'receive', 'download', 'mail']],
    ['📦', 'Package', ['package', 'box', 'delivery', 'shipping', 'parcel']],
    ['📫', 'Closed Mailbox with Raised Flag', ['mailbox', 'mail', 'inbox']],
    ['📬', 'Open Mailbox with Raised Flag', ['mailbox', 'mail', 'inbox']],
    ['📭', 'Open Mailbox with Lowered Flag', ['mailbox', 'empty', 'no mail']],
    ['📮', 'Postbox', ['postbox', 'mail', 'send', 'letter']],

    # Time
    ['⏰', 'Alarm Clock', ['alarm', 'clock', 'time', 'wake up', 'morning']],
    ['⏱️', 'Stopwatch', ['stopwatch', 'timer', 'time', 'speed']],
    ['⏲️', 'Timer Clock', ['timer', 'clock', 'countdown', 'time']],
    ['🕐', 'One O\'Clock', ['1', 'one', 'clock', 'time']],
    ['🕑', 'Two O\'Clock', ['2', 'two', 'clock', 'time']],
    ['🕒', 'Three O\'Clock', ['3', 'three', 'clock', 'time']],
    ['🕓', 'Four O\'Clock', ['4', 'four', 'clock', 'time']],
    ['🕔', 'Five O\'Clock', ['5', 'five', 'clock', 'time']],
    ['🕕', 'Six O\'Clock', ['6', 'six', 'clock', 'time']],
    ['🕖', 'Seven O\'Clock', ['7', 'seven', 'clock', 'time']],
    ['🕗', 'Eight O\'Clock', ['8', 'eight', 'clock', 'time']],
    ['🕘', 'Nine O\'Clock', ['9', 'nine', 'clock', 'time']],
    ['🕙', 'Ten O\'Clock', ['10', 'ten', 'clock', 'time']],
    ['🕚', 'Eleven O\'Clock', ['11', 'eleven', 'clock', 'time']],
    ['🕛', 'Twelve O\'Clock', ['12', 'twelve', 'clock', 'time', 'noon', 'midnight']],
    ['⌛', 'Hourglass Done', ['hourglass', 'time', 'wait', 'done']],
    ['⏳', 'Hourglass Not Done', ['hourglass', 'time', 'wait', 'loading', 'pending']],

    # Misc
    ['🎵', 'Musical Note', ['music', 'note', 'song', 'melody', 'sound']],
    ['🎶', 'Musical Notes', ['music', 'notes', 'song', 'melody', 'singing']],
    ['🎼', 'Musical Score', ['music', 'score', 'sheet music', 'notes']],
    ['🎹', 'Musical Keyboard', ['piano', 'keyboard', 'music', 'keys']],
    ['🎸', 'Guitar', ['guitar', 'music', 'rock', 'instrument']],
    ['🎺', 'Trumpet', ['trumpet', 'music', 'brass', 'instrument']],
    ['🎻', 'Violin', ['violin', 'music', 'classical', 'instrument']],
    ['🥁', 'Drum', ['drum', 'music', 'percussion', 'instrument']],
    ['🎷', 'Saxophone', ['saxophone', 'music', 'jazz', 'instrument']],
    ['🪕', 'Banjo', ['banjo', 'music', 'country', 'instrument']],
    ['🎨', 'Artist Palette', ['art', 'paint', 'palette', 'creative', 'design']],
    ['🎭', 'Performing Arts', ['theater', 'drama', 'masks', 'acting', 'performance']],
    ['🎪', 'Circus Tent', ['circus', 'tent', 'carnival', 'fair']],
    ['🎟️', 'Admission Tickets', ['ticket', 'admission', 'event', 'movie']],
    ['🎫', 'Ticket', ['ticket', 'event', 'admission', 'pass']],
    ['🧸', 'Teddy Bear', ['teddy', 'bear', 'toy', 'cute', 'stuffed']],
    ['🪀', 'Yo-Yo', ['yo-yo', 'toy', 'play', 'string']],
    ['🪁', 'Kite', ['kite', 'fly', 'wind', 'toy']],
    ['🔮', 'Crystal Ball', ['crystal ball', 'fortune', 'magic', 'future', 'predict']],
    ['🧿', 'Nazar Amulet', ['evil eye', 'amulet', 'protection', 'luck']],
    ['🪄', 'Magic Wand', ['magic', 'wand', 'wizard', 'spell']],
    ['🧙', 'Mage', ['wizard', 'mage', 'magic', 'fantasy']],
    ['🧚', 'Fairy', ['fairy', 'magic', 'fantasy', 'wings']],
    ['🧜', 'Merperson', ['mermaid', 'merman', 'ocean', 'sea', 'fantasy']],
    ['🧝', 'Elf', ['elf', 'fantasy', 'magic', 'tolkien']],
    ['🧞', 'Genie', ['genie', 'wish', 'lamp', 'magic']],
    ['🧟', 'Zombie', ['zombie', 'undead', 'horror', 'halloween']],
    ['🦸', 'Superhero', ['superhero', 'hero', 'power', 'cape']],
    ['🦹', 'Supervillain', ['villain', 'evil', 'bad', 'supervillain']],
    ['🤴', 'Prince', ['prince', 'royal', 'king', 'crown']],
    ['👸', 'Princess', ['princess', 'royal', 'queen', 'crown', 'tiara']],
    ['👰', 'Person with Veil', ['bride', 'wedding', 'marriage', 'veil']],
    ['🤵', 'Person in Tuxedo', ['groom', 'wedding', 'tuxedo', 'formal']],
    ['👼', 'Baby Angel', ['angel', 'baby', 'cherub', 'innocent']],
    ['🎅', 'Santa Claus', ['santa', 'christmas', 'xmas', 'holiday']],
    ['🤶', 'Mrs. Claus', ['mrs claus', 'christmas', 'xmas', 'holiday']],
    ['🧑‍🎄', 'Mx Claus', ['mx claus', 'christmas', 'xmas', 'holiday']],
    ['👁️‍🗨️', 'Eye in Speech Bubble', ['witness', 'eye', 'speech', 'awareness']],
    ['🗣️', 'Speaking Head', ['speaking', 'talk', 'voice', 'speech']],
    ['👤', 'Bust in Silhouette', ['person', 'user', 'profile', 'silhouette', 'account']],
    ['👥', 'Busts in Silhouette', ['people', 'users', 'group', 'team', 'profiles']],
    ['🫂', 'People Hugging', ['hug', 'embrace', 'comfort', 'support', 'friends']],
    ['👣', 'Footprints', ['footprints', 'feet', 'walk', 'steps', 'tracks']],
    ['🐾', 'Paw Prints', ['paw', 'pet', 'dog', 'cat', 'animal', 'tracks']],
    ['🫡', 'Saluting Face', ['salute', 'respect', 'yes sir', 'military', 'honor']],
    ['🫠', 'Melting Face', ['melt', 'hot', 'embarrassed', 'disappear', 'sarcasm']],
    ['🫣', 'Face with Peeking Eye', ['peek', 'shy', 'scared', 'nervous', 'curious']],
    ['🫤', 'Face with Diagonal Mouth', ['meh', 'skeptical', 'unsure', 'disappointed']],
    ['🫥', 'Dotted Line Face', ['invisible', 'hidden', 'disappear', 'introvert']],
    ['🫨', 'Shaking Face', ['shake', '震える', 'shock', 'vibrate', 'earthquake']],
    ['🩷', 'Pink Heart', ['love', 'heart', 'pink', 'cute', 'affection']],
    ['🩵', 'Light Blue Heart', ['love', 'heart', 'light blue', 'sky', 'calm']],
    ['🩶', 'Grey Heart', ['love', 'heart', 'grey', 'gray', 'neutral']],
    ['🪿', 'Goose', ['goose', 'honk', 'bird', 'animal', 'untitled']],
    ['🫎', 'Moose', ['moose', 'elk', 'animal', 'canada']],
    ['🪻', 'Hyacinth', ['flower', 'hyacinth', 'purple', 'spring']],
    ['🪼', 'Jellyfish', ['jellyfish', 'ocean', 'sea', 'sting']],
    ['🪽', 'Wing', ['wing', 'angel', 'fly', 'bird', 'feather']],
    ['🪾', 'Scooter', ['scooter', 'disability', 'mobility', 'wheelchair']],
    ['🛜', 'Wireless', ['wifi', 'wireless', 'internet', 'network', 'signal']],

    # Flags
    ['🏁', 'Chequered Flag', ['finish', 'race', 'checkered', 'flag', 'end']],
    ['🚩', 'Triangular Flag', ['flag', 'red flag', 'warning', 'marker']],
    ['🎌', 'Crossed Flags', ['flags', 'japan', 'celebration']],
    ['🏴', 'Black Flag', ['flag', 'black', 'pirate']],
    ['🏳️', 'White Flag', ['flag', 'white', 'surrender', 'peace']],
    ['🏳️‍🌈', 'Rainbow Flag', ['pride', 'lgbtq', 'rainbow', 'gay', 'flag']],
    ['🏳️‍⚧️', 'Transgender Flag', ['transgender', 'trans', 'pride', 'flag']],
    ['🏴‍☠️', 'Pirate Flag', ['pirate', 'skull', 'jolly roger', 'flag']],

    # Country flags
    ['🇺🇸', 'Flag: United States', ['usa', 'america', 'united states', 'flag', 'us']],
    ['🇬🇧', 'Flag: United Kingdom', ['uk', 'britain', 'england', 'united kingdom', 'flag', 'gb']],
    ['🇨🇦', 'Flag: Canada', ['canada', 'flag', 'ca', 'maple']],
    ['🇦🇺', 'Flag: Australia', ['australia', 'flag', 'au', 'aussie']],
    ['🇩🇪', 'Flag: Germany', ['germany', 'flag', 'de', 'german']],
    ['🇫🇷', 'Flag: France', ['france', 'flag', 'fr', 'french']],
    ['🇯🇵', 'Flag: Japan', ['japan', 'flag', 'jp', 'japanese']],
    ['🇰🇷', 'Flag: South Korea', ['korea', 'south korea', 'flag', 'kr', 'korean']],
    ['🇨🇳', 'Flag: China', ['china', 'flag', 'cn', 'chinese']],
    ['🇮🇳', 'Flag: India', ['india', 'flag', 'in', 'indian']],
    ['🇧🇷', 'Flag: Brazil', ['brazil', 'flag', 'br', 'brazilian']],
    ['🇲🇽', 'Flag: Mexico', ['mexico', 'flag', 'mx', 'mexican']],
    ['🇮🇹', 'Flag: Italy', ['italy', 'flag', 'it', 'italian']],
    ['🇪🇸', 'Flag: Spain', ['spain', 'flag', 'es', 'spanish']],
    ['🇷🇺', 'Flag: Russia', ['russia', 'flag', 'ru', 'russian']],

    # Additional common emojis
    ['💬', 'Speech Balloon', ['speech', 'chat', 'talk', 'message', 'comment', 'bubble']],
    ['💭', 'Thought Balloon', ['thought', 'think', 'bubble', 'idea']],
    ['🗯️', 'Right Anger Bubble', ['anger', 'angry', 'speech', 'yell']],
    ['💤', 'Zzz', ['sleep', 'zzz', 'tired', 'snore', 'nap']],
    ['💢', 'Anger Symbol', ['anger', 'angry', 'mad', 'frustration']],
    ['💥', 'Collision', ['boom', 'explosion', 'collision', 'crash', 'bang']],
    ['💦', 'Sweat Droplets', ['sweat', 'water', 'splash', 'effort', 'work']],
    ['💨', 'Dashing Away', ['dash', 'fast', 'run', 'wind', 'speed', 'whoosh']],
    ['🕳️', 'Hole', ['hole', 'empty', 'void', 'pit']],
    ['👨‍💻', 'Man Technologist', ['developer', 'programmer', 'coder', 'tech', 'man', 'software']],
    ['👩‍💻', 'Woman Technologist', ['developer', 'programmer', 'coder', 'tech', 'woman', 'software']],
    ['🧑‍💻', 'Technologist', ['developer', 'programmer', 'coder', 'tech', 'software', 'engineer']],
    ['👨‍🔬', 'Man Scientist', ['scientist', 'research', 'lab', 'man', 'science']],
    ['👩‍🔬', 'Woman Scientist', ['scientist', 'research', 'lab', 'woman', 'science']],
    ['👨‍🎨', 'Man Artist', ['artist', 'painter', 'creative', 'man', 'art']],
    ['👩‍🎨', 'Woman Artist', ['artist', 'painter', 'creative', 'woman', 'art']],
    ['👨‍🚀', 'Man Astronaut', ['astronaut', 'space', 'nasa', 'man', 'rocket']],
    ['👩‍🚀', 'Woman Astronaut', ['astronaut', 'space', 'nasa', 'woman', 'rocket']],
    ['👨‍🍳', 'Man Cook', ['chef', 'cook', 'food', 'man', 'kitchen']],
    ['👩‍🍳', 'Woman Cook', ['chef', 'cook', 'food', 'woman', 'kitchen']],
    ['🧑‍🍳', 'Cook', ['chef', 'cook', 'food', 'kitchen']],
    ['👨‍⚕️', 'Man Health Worker', ['doctor', 'nurse', 'medical', 'man', 'health']],
    ['👩‍⚕️', 'Woman Health Worker', ['doctor', 'nurse', 'medical', 'woman', 'health']],
    ['👨‍🏫', 'Man Teacher', ['teacher', 'professor', 'education', 'man', 'school']],
    ['👩‍🏫', 'Woman Teacher', ['teacher', 'professor', 'education', 'woman', 'school']],
    ['👨‍🎓', 'Man Student', ['student', 'graduate', 'education', 'man', 'school']],
    ['👩‍🎓', 'Woman Student', ['student', 'graduate', 'education', 'woman', 'school']],
    ['🧑‍🎓', 'Student', ['student', 'graduate', 'education', 'school']],
);

# Unicode characters (only searched when unicode_enabled is true)
my @unicode_chars = (
    # Arrows
    ['→', 'Rightwards Arrow', ['arrow', 'right', 'direction', 'next', 'forward', 'then']],
    ['←', 'Leftwards Arrow', ['arrow', 'left', 'direction', 'back', 'previous']],
    ['↑', 'Upwards Arrow', ['arrow', 'up', 'direction', 'increase']],
    ['↓', 'Downwards Arrow', ['arrow', 'down', 'direction', 'decrease']],
    ['↔', 'Left Right Arrow', ['arrow', 'horizontal', 'both', 'bidirectional']],
    ['↕', 'Up Down Arrow', ['arrow', 'vertical', 'both', 'bidirectional']],
    ['↗', 'North East Arrow', ['arrow', 'diagonal', 'up right', 'northeast']],
    ['↘', 'South East Arrow', ['arrow', 'diagonal', 'down right', 'southeast']],
    ['↙', 'South West Arrow', ['arrow', 'diagonal', 'down left', 'southwest']],
    ['↖', 'North West Arrow', ['arrow', 'diagonal', 'up left', 'northwest']],
    ['⇒', 'Rightwards Double Arrow', ['arrow', 'implies', 'therefore', 'double', 'logic']],
    ['⇐', 'Leftwards Double Arrow', ['arrow', 'implied by', 'double', 'logic']],
    ['⇔', 'Left Right Double Arrow', ['arrow', 'equivalent', 'iff', 'double', 'logic']],
    ['⇑', 'Upwards Double Arrow', ['arrow', 'double', 'up']],
    ['⇓', 'Downwards Double Arrow', ['arrow', 'double', 'down']],
    ['⟶', 'Long Rightwards Arrow', ['arrow', 'long', 'maps to', 'function']],
    ['⟵', 'Long Leftwards Arrow', ['arrow', 'long', 'back']],
    ['⟷', 'Long Left Right Arrow', ['arrow', 'long', 'bidirectional']],
    ['↩', 'Leftwards Arrow with Hook', ['arrow', 'return', 'enter', 'hook']],
    ['↪', 'Rightwards Arrow with Hook', ['arrow', 'hook', 'redirect']],
    ['⤴', 'Arrow Pointing Rightwards Then Curving Upwards', ['arrow', 'curve', 'up']],
    ['⤵', 'Arrow Pointing Rightwards Then Curving Downwards', ['arrow', 'curve', 'down']],

    # Mathematical Operators
    ['×', 'Multiplication Sign', ['multiply', 'times', 'x', 'cross', 'math']],
    ['÷', 'Division Sign', ['divide', 'division', 'math', 'obelus']],
    ['±', 'Plus-Minus Sign', ['plus minus', 'plus or minus', 'math', 'tolerance']],
    ['∓', 'Minus-Plus Sign', ['minus plus', 'math']],
    ['√', 'Square Root', ['square root', 'root', 'radical', 'math', 'sqrt']],
    ['∛', 'Cube Root', ['cube root', 'root', 'math']],
    ['∜', 'Fourth Root', ['fourth root', 'root', 'math']],
    ['∞', 'Infinity', ['infinity', 'forever', 'endless', 'math', 'unlimited']],
    ['≈', 'Almost Equal To', ['approximately', 'about', 'roughly', 'almost equal', 'math']],
    ['≠', 'Not Equal To', ['not equal', 'different', 'unequal', 'math', 'inequality']],
    ['≡', 'Identical To', ['identical', 'equivalent', 'congruent', 'math']],
    ['≢', 'Not Identical To', ['not identical', 'math']],
    ['≤', 'Less-Than or Equal To', ['less than or equal', 'lte', 'at most', 'math']],
    ['≥', 'Greater-Than or Equal To', ['greater than or equal', 'gte', 'at least', 'math']],
    ['≪', 'Much Less-Than', ['much less', 'math']],
    ['≫', 'Much Greater-Than', ['much greater', 'math']],
    ['∝', 'Proportional To', ['proportional', 'math', 'varies']],
    ['∑', 'N-Ary Summation', ['sum', 'sigma', 'summation', 'math', 'total']],
    ['∏', 'N-Ary Product', ['product', 'pi', 'math', 'multiply all']],
    ['∫', 'Integral', ['integral', 'calculus', 'math', 'integrate']],
    ['∬', 'Double Integral', ['double integral', 'calculus', 'math']],
    ['∮', 'Contour Integral', ['contour integral', 'line integral', 'calculus', 'math']],
    ['∂', 'Partial Differential', ['partial', 'derivative', 'calculus', 'math', 'del']],
    ['∇', 'Nabla', ['nabla', 'del', 'gradient', 'math', 'vector']],
    ['∆', 'Increment', ['delta', 'change', 'difference', 'triangle', 'math']],
    ['∈', 'Element Of', ['element of', 'in', 'belongs to', 'member', 'set', 'math']],
    ['∉', 'Not an Element Of', ['not element of', 'not in', 'set', 'math']],
    ['∋', 'Contains as Member', ['contains', 'has element', 'set', 'math']],
    ['⊂', 'Subset Of', ['subset', 'contained in', 'set', 'math']],
    ['⊃', 'Superset Of', ['superset', 'contains', 'set', 'math']],
    ['⊆', 'Subset of or Equal To', ['subset or equal', 'set', 'math']],
    ['⊇', 'Superset of or Equal To', ['superset or equal', 'set', 'math']],
    ['∪', 'Union', ['union', 'or', 'set', 'math', 'cup']],
    ['∩', 'Intersection', ['intersection', 'and', 'set', 'math', 'cap']],
    ['∅', 'Empty Set', ['empty set', 'null', 'void', 'nothing', 'math']],
    ['∴', 'Therefore', ['therefore', 'so', 'hence', 'thus', 'logic', 'math']],
    ['∵', 'Because', ['because', 'since', 'logic', 'math']],
    ['∀', 'For All', ['for all', 'universal', 'every', 'logic', 'math']],
    ['∃', 'There Exists', ['exists', 'there exists', 'some', 'logic', 'math']],
    ['∄', 'There Does Not Exist', ['not exists', 'logic', 'math']],
    ['¬', 'Not Sign', ['not', 'negation', 'logic', 'math']],
    ['∧', 'Logical And', ['and', 'conjunction', 'logic', 'math', 'wedge']],
    ['∨', 'Logical Or', ['or', 'disjunction', 'logic', 'math', 'vee']],
    ['⊕', 'Circled Plus', ['xor', 'exclusive or', 'direct sum', 'math']],
    ['⊗', 'Circled Times', ['tensor', 'kronecker', 'math']],
    ['⊥', 'Up Tack', ['perpendicular', 'orthogonal', 'bottom', 'false', 'math']],
    ['∥', 'Parallel To', ['parallel', 'math']],
    ['∠', 'Angle', ['angle', 'math', 'geometry']],
    ['∟', 'Right Angle', ['right angle', '90 degrees', 'math', 'geometry']],
    ['°', 'Degree Sign', ['degree', 'temperature', 'angle', 'celsius', 'fahrenheit']],
    ['′', 'Prime', ['prime', 'minutes', 'feet', 'derivative', 'math']],
    ['″', 'Double Prime', ['double prime', 'seconds', 'inches', 'math']],
    ['‰', 'Per Mille Sign', ['per mille', 'permille', 'thousandth', 'math']],
    ['‱', 'Per Ten Thousand Sign', ['per ten thousand', 'basis point', 'math']],
    ['ℵ', 'Alef Symbol', ['aleph', 'infinity', 'cardinal', 'set theory', 'math']],

    # Greek Letters (commonly used in math/science)
    ['α', 'Greek Small Letter Alpha', ['alpha', 'greek', 'math', 'science']],
    ['β', 'Greek Small Letter Beta', ['beta', 'greek', 'math', 'science']],
    ['γ', 'Greek Small Letter Gamma', ['gamma', 'greek', 'math', 'science']],
    ['δ', 'Greek Small Letter Delta', ['delta', 'greek', 'math', 'science', 'change']],
    ['ε', 'Greek Small Letter Epsilon', ['epsilon', 'greek', 'math', 'small']],
    ['ζ', 'Greek Small Letter Zeta', ['zeta', 'greek', 'math']],
    ['η', 'Greek Small Letter Eta', ['eta', 'greek', 'math', 'efficiency']],
    ['θ', 'Greek Small Letter Theta', ['theta', 'greek', 'math', 'angle']],
    ['ι', 'Greek Small Letter Iota', ['iota', 'greek', 'small amount']],
    ['κ', 'Greek Small Letter Kappa', ['kappa', 'greek', 'math']],
    ['λ', 'Greek Small Letter Lambda', ['lambda', 'greek', 'math', 'wavelength', 'function']],
    ['μ', 'Greek Small Letter Mu', ['mu', 'greek', 'math', 'micro', 'mean']],
    ['ν', 'Greek Small Letter Nu', ['nu', 'greek', 'math', 'frequency']],
    ['ξ', 'Greek Small Letter Xi', ['xi', 'greek', 'math']],
    ['ο', 'Greek Small Letter Omicron', ['omicron', 'greek']],
    ['π', 'Greek Small Letter Pi', ['pi', 'greek', 'math', '3.14', 'circle']],
    ['ρ', 'Greek Small Letter Rho', ['rho', 'greek', 'math', 'density']],
    ['σ', 'Greek Small Letter Sigma', ['sigma', 'greek', 'math', 'standard deviation']],
    ['τ', 'Greek Small Letter Tau', ['tau', 'greek', 'math', 'torque', 'time constant']],
    ['υ', 'Greek Small Letter Upsilon', ['upsilon', 'greek']],
    ['φ', 'Greek Small Letter Phi', ['phi', 'greek', 'math', 'golden ratio']],
    ['χ', 'Greek Small Letter Chi', ['chi', 'greek', 'math', 'chi-squared']],
    ['ψ', 'Greek Small Letter Psi', ['psi', 'greek', 'math', 'wave function']],
    ['ω', 'Greek Small Letter Omega', ['omega', 'greek', 'math', 'angular velocity', 'ohm']],
    ['Α', 'Greek Capital Letter Alpha', ['Alpha', 'greek', 'capital']],
    ['Β', 'Greek Capital Letter Beta', ['Beta', 'greek', 'capital']],
    ['Γ', 'Greek Capital Letter Gamma', ['Gamma', 'greek', 'capital', 'math']],
    ['Δ', 'Greek Capital Letter Delta', ['Delta', 'greek', 'capital', 'change', 'difference']],
    ['Θ', 'Greek Capital Letter Theta', ['Theta', 'greek', 'capital', 'angle']],
    ['Λ', 'Greek Capital Letter Lambda', ['Lambda', 'greek', 'capital']],
    ['Π', 'Greek Capital Letter Pi', ['Pi', 'greek', 'capital', 'product']],
    ['Σ', 'Greek Capital Letter Sigma', ['Sigma', 'greek', 'capital', 'sum', 'summation']],
    ['Φ', 'Greek Capital Letter Phi', ['Phi', 'greek', 'capital']],
    ['Ψ', 'Greek Capital Letter Psi', ['Psi', 'greek', 'capital']],
    ['Ω', 'Greek Capital Letter Omega', ['Omega', 'greek', 'capital', 'ohm', 'resistance']],

    # Currency Symbols
    ['€', 'Euro Sign', ['euro', 'currency', 'money', 'europe', 'eur']],
    ['£', 'Pound Sign', ['pound', 'currency', 'money', 'british', 'gbp', 'sterling']],
    ['¥', 'Yen Sign', ['yen', 'yuan', 'currency', 'money', 'japan', 'china', 'jpy', 'cny']],
    ['₹', 'Indian Rupee Sign', ['rupee', 'currency', 'money', 'india', 'inr']],
    ['₿', 'Bitcoin Sign', ['bitcoin', 'btc', 'crypto', 'cryptocurrency', 'money']],
    ['₽', 'Ruble Sign', ['ruble', 'rouble', 'currency', 'money', 'russia', 'rub']],
    ['₩', 'Won Sign', ['won', 'currency', 'money', 'korea', 'krw']],
    ['฿', 'Thai Baht Sign', ['baht', 'currency', 'money', 'thailand', 'thb']],
    ['₫', 'Dong Sign', ['dong', 'currency', 'money', 'vietnam', 'vnd']],
    ['₴', 'Hryvnia Sign', ['hryvnia', 'currency', 'money', 'ukraine', 'uah']],
    ['₸', 'Tenge Sign', ['tenge', 'currency', 'money', 'kazakhstan', 'kzt']],
    ['₺', 'Turkish Lira Sign', ['lira', 'currency', 'money', 'turkey', 'try']],
    ['₾', 'Lari Sign', ['lari', 'currency', 'money', 'georgia', 'gel']],
    ['¢', 'Cent Sign', ['cent', 'currency', 'money', 'penny']],
    ['¤', 'Currency Sign', ['currency', 'money', 'generic']],

    # Typography & Punctuation
    ['—', 'Em Dash', ['em dash', 'dash', 'long dash', 'punctuation']],
    ['–', 'En Dash', ['en dash', 'dash', 'range', 'punctuation']],
    ['…', 'Horizontal Ellipsis', ['ellipsis', 'dots', 'three dots', 'etc', 'punctuation']],
    ['•', 'Bullet', ['bullet', 'dot', 'list', 'point']],
    ['·', 'Middle Dot', ['middle dot', 'interpunct', 'bullet', 'multiplication']],
    ['‣', 'Triangular Bullet', ['bullet', 'triangle', 'list']],
    ['※', 'Reference Mark', ['reference', 'note', 'asterisk', 'japanese']],
    ['†', 'Dagger', ['dagger', 'cross', 'footnote', 'death']],
    ['‡', 'Double Dagger', ['double dagger', 'footnote']],
    ['§', 'Section Sign', ['section', 'law', 'legal', 'paragraph']],
    ['¶', 'Pilcrow Sign', ['paragraph', 'pilcrow', 'formatting']],
    ['«', 'Left-Pointing Double Angle Quotation Mark', ['guillemet', 'quote', 'french', 'left']],
    ['»', 'Right-Pointing Double Angle Quotation Mark', ['guillemet', 'quote', 'french', 'right']],
    ["\x{2018}", 'Left Single Quotation Mark', ['quote', 'apostrophe', 'left', 'curly']],
    ["\x{2019}", 'Right Single Quotation Mark', ['quote', 'apostrophe', 'right', 'curly']],
    ["\x{201C}", 'Left Double Quotation Mark', ['quote', 'double', 'left', 'curly']],
    ["\x{201D}", 'Right Double Quotation Mark', ['quote', 'double', 'right', 'curly']],
    ['‹', 'Single Left-Pointing Angle Quotation Mark', ['quote', 'angle', 'left']],
    ['›', 'Single Right-Pointing Angle Quotation Mark', ['quote', 'angle', 'right']],
    ["\x{201E}", 'Double Low-9 Quotation Mark', ['quote', 'german', 'low']],
    ["\x{201A}", 'Single Low-9 Quotation Mark', ['quote', 'german', 'low']],
    ['′', 'Prime', ['prime', 'feet', 'minutes', 'math']],
    ['″', 'Double Prime', ['double prime', 'inches', 'seconds', 'math']],
    ['‴', 'Triple Prime', ['triple prime', 'math']],
    ['⁂', 'Asterism', ['asterism', 'section break', 'stars']],
    ['№', 'Numero Sign', ['numero', 'number', 'no']],
    ['℃', 'Degree Celsius', ['celsius', 'temperature', 'centigrade', 'metric']],
    ['℉', 'Degree Fahrenheit', ['fahrenheit', 'temperature', 'imperial']],
    ['℗', 'Sound Recording Copyright', ['phonogram', 'copyright', 'sound', 'recording']],
    ['℠', 'Service Mark', ['service mark', 'sm', 'trademark']],
    ['ℹ', 'Information Source', ['info', 'information', 'help']],
    ['⁊', 'Tironian Et Sign', ['and', 'tironian', 'ampersand']],
    ['&', 'Ampersand', ['ampersand', 'and', 'et']],
    ['@', 'Commercial At', ['at', 'email', 'at sign']],
    ['#', 'Number Sign', ['hash', 'hashtag', 'number', 'pound']],
    ['*', 'Asterisk', ['asterisk', 'star', 'multiply', 'wildcard']],
    ['⁑', 'Two Asterisks Aligned Vertically', ['asterisks', 'footnote']],
    ['⁕', 'Flower Punctuation Mark', ['flower', 'asterisk', 'ornament']],
    ['|', 'Vertical Line', ['pipe', 'vertical bar', 'or', 'shell']],
    ['¦', 'Broken Bar', ['broken bar', 'pipe', 'vertical']],
    ['‖', 'Double Vertical Line', ['double pipe', 'parallel', 'math']],
    ['⁄', 'Fraction Slash', ['fraction', 'slash', 'divide']],
    ['⌀', 'Diameter Sign', ['diameter', 'phi', 'circle']],

    # Fractions & Numbers
    ['½', 'Vulgar Fraction One Half', ['half', 'fraction', '1/2', '0.5']],
    ['⅓', 'Vulgar Fraction One Third', ['third', 'fraction', '1/3']],
    ['⅔', 'Vulgar Fraction Two Thirds', ['two thirds', 'fraction', '2/3']],
    ['¼', 'Vulgar Fraction One Quarter', ['quarter', 'fourth', 'fraction', '1/4', '0.25']],
    ['¾', 'Vulgar Fraction Three Quarters', ['three quarters', 'fraction', '3/4', '0.75']],
    ['⅕', 'Vulgar Fraction One Fifth', ['fifth', 'fraction', '1/5']],
    ['⅖', 'Vulgar Fraction Two Fifths', ['two fifths', 'fraction', '2/5']],
    ['⅗', 'Vulgar Fraction Three Fifths', ['three fifths', 'fraction', '3/5']],
    ['⅘', 'Vulgar Fraction Four Fifths', ['four fifths', 'fraction', '4/5']],
    ['⅙', 'Vulgar Fraction One Sixth', ['sixth', 'fraction', '1/6']],
    ['⅚', 'Vulgar Fraction Five Sixths', ['five sixths', 'fraction', '5/6']],
    ['⅛', 'Vulgar Fraction One Eighth', ['eighth', 'fraction', '1/8']],
    ['⅜', 'Vulgar Fraction Three Eighths', ['three eighths', 'fraction', '3/8']],
    ['⅝', 'Vulgar Fraction Five Eighths', ['five eighths', 'fraction', '5/8']],
    ['⅞', 'Vulgar Fraction Seven Eighths', ['seven eighths', 'fraction', '7/8']],
    ['⁰', 'Superscript Zero', ['superscript', 'zero', 'power', 'exponent']],
    ['¹', 'Superscript One', ['superscript', 'one', 'first', 'power', 'exponent']],
    ['²', 'Superscript Two', ['superscript', 'two', 'squared', 'power', 'exponent']],
    ['³', 'Superscript Three', ['superscript', 'three', 'cubed', 'power', 'exponent']],
    ['⁴', 'Superscript Four', ['superscript', 'four', 'power', 'exponent']],
    ['⁵', 'Superscript Five', ['superscript', 'five', 'power', 'exponent']],
    ['⁶', 'Superscript Six', ['superscript', 'six', 'power', 'exponent']],
    ['⁷', 'Superscript Seven', ['superscript', 'seven', 'power', 'exponent']],
    ['⁸', 'Superscript Eight', ['superscript', 'eight', 'power', 'exponent']],
    ['⁹', 'Superscript Nine', ['superscript', 'nine', 'power', 'exponent']],
    ['⁺', 'Superscript Plus Sign', ['superscript', 'plus', 'positive']],
    ['⁻', 'Superscript Minus', ['superscript', 'minus', 'negative']],
    ['⁼', 'Superscript Equals Sign', ['superscript', 'equals']],
    ['⁽', 'Superscript Left Parenthesis', ['superscript', 'parenthesis', 'left']],
    ['⁾', 'Superscript Right Parenthesis', ['superscript', 'parenthesis', 'right']],
    ['ⁿ', 'Superscript Latin Small Letter N', ['superscript', 'n', 'power']],
    ['₀', 'Subscript Zero', ['subscript', 'zero']],
    ['₁', 'Subscript One', ['subscript', 'one']],
    ['₂', 'Subscript Two', ['subscript', 'two']],
    ['₃', 'Subscript Three', ['subscript', 'three']],
    ['₄', 'Subscript Four', ['subscript', 'four']],
    ['₅', 'Subscript Five', ['subscript', 'five']],
    ['₆', 'Subscript Six', ['subscript', 'six']],
    ['₇', 'Subscript Seven', ['subscript', 'seven']],
    ['₈', 'Subscript Eight', ['subscript', 'eight']],
    ['₉', 'Subscript Nine', ['subscript', 'nine']],
    ['₊', 'Subscript Plus Sign', ['subscript', 'plus']],
    ['₋', 'Subscript Minus', ['subscript', 'minus']],
    ['₌', 'Subscript Equals Sign', ['subscript', 'equals']],
    ['₍', 'Subscript Left Parenthesis', ['subscript', 'parenthesis', 'left']],
    ['₎', 'Subscript Right Parenthesis', ['subscript', 'parenthesis', 'right']],

    # Geometric Shapes
    ['●', 'Black Circle', ['circle', 'filled', 'dot', 'bullet']],
    ['○', 'White Circle', ['circle', 'empty', 'ring', 'outline']],
    ['◉', 'Fisheye', ['circle', 'bullseye', 'target', 'radio button']],
    ['◎', 'Bullseye', ['circle', 'target', 'bullseye', 'double']],
    ['◌', 'Dotted Circle', ['circle', 'dotted', 'placeholder']],
    ['◐', 'Circle with Left Half Black', ['circle', 'half', 'contrast']],
    ['◑', 'Circle with Right Half Black', ['circle', 'half', 'contrast']],
    ['◒', 'Circle with Lower Half Black', ['circle', 'half', 'contrast']],
    ['◓', 'Circle with Upper Half Black', ['circle', 'half', 'contrast']],
    ['■', 'Black Square', ['square', 'filled', 'block']],
    ['□', 'White Square', ['square', 'empty', 'outline', 'checkbox']],
    ['▪', 'Black Small Square', ['square', 'small', 'bullet']],
    ['▫', 'White Small Square', ['square', 'small', 'outline']],
    ['▬', 'Black Rectangle', ['rectangle', 'bar', 'filled']],
    ['▭', 'White Rectangle', ['rectangle', 'bar', 'outline']],
    ['▲', 'Black Up-Pointing Triangle', ['triangle', 'up', 'filled', 'arrow']],
    ['△', 'White Up-Pointing Triangle', ['triangle', 'up', 'outline', 'delta']],
    ['▼', 'Black Down-Pointing Triangle', ['triangle', 'down', 'filled', 'arrow']],
    ['▽', 'White Down-Pointing Triangle', ['triangle', 'down', 'outline', 'nabla']],
    ['◀', 'Black Left-Pointing Triangle', ['triangle', 'left', 'filled', 'previous', 'back']],
    ['◁', 'White Left-Pointing Triangle', ['triangle', 'left', 'outline']],
    ['▶', 'Black Right-Pointing Triangle', ['triangle', 'right', 'filled', 'play', 'next']],
    ['▷', 'White Right-Pointing Triangle', ['triangle', 'right', 'outline']],
    ['◆', 'Black Diamond', ['diamond', 'filled', 'rhombus']],
    ['◇', 'White Diamond', ['diamond', 'outline', 'rhombus']],
    ['◈', 'White Diamond Containing Black Small Diamond', ['diamond', 'nested']],
    ['★', 'Black Star', ['star', 'filled', 'favorite', 'rating']],
    ['☆', 'White Star', ['star', 'outline', 'favorite', 'rating']],
    ['✦', 'Black Four Pointed Star', ['star', 'four point', 'sparkle']],
    ['✧', 'White Four Pointed Star', ['star', 'four point', 'sparkle', 'outline']],
    ['✪', 'Circled White Star', ['star', 'circle', 'badge']],
    ['✫', 'Open Centre Black Star', ['star', 'open', 'badge']],
    ['✬', 'Black Centre White Star', ['star', 'badge']],
    ['✭', 'Outlined Black Star', ['star', 'outlined']],
    ['✮', 'Heavy Outlined Black Star', ['star', 'heavy', 'outlined']],
    ['✯', 'Pinwheel Star', ['star', 'pinwheel']],
    ['✰', 'Shadowed White Star', ['star', 'shadow', '3d']],
    ['✱', 'Heavy Asterisk', ['asterisk', 'star', 'heavy']],
    ['✲', 'Open Centre Asterisk', ['asterisk', 'open']],
    ['❖', 'Black Diamond Minus White X', ['diamond', 'ornament']],
    ['❤', 'Heavy Black Heart', ['heart', 'love', 'filled']],
    ['❥', 'Rotated Heavy Black Heart Bullet', ['heart', 'bullet']],
    ['❦', 'Floral Heart', ['heart', 'floral', 'ornament']],
    ['❧', 'Rotated Floral Heart Bullet', ['heart', 'floral', 'bullet']],

    # Miscellaneous Symbols
    ['✓', 'Check Mark', ['check', 'tick', 'yes', 'correct', 'done', 'approved']],
    ['✔', 'Heavy Check Mark', ['check', 'tick', 'yes', 'correct', 'done', 'heavy']],
    ['✗', 'Ballot X', ['x', 'cross', 'no', 'wrong', 'delete']],
    ['✘', 'Heavy Ballot X', ['x', 'cross', 'no', 'wrong', 'delete', 'heavy']],
    ['✕', 'Multiplication X', ['x', 'multiply', 'times', 'close']],
    ['✖', 'Heavy Multiplication X', ['x', 'multiply', 'times', 'close', 'heavy']],
    ['☐', 'Ballot Box', ['checkbox', 'empty', 'unchecked', 'todo']],
    ['☑', 'Ballot Box with Check', ['checkbox', 'checked', 'done', 'todo']],
    ['☒', 'Ballot Box with X', ['checkbox', 'x', 'rejected', 'cancelled']],
    ['✉', 'Envelope', ['envelope', 'email', 'mail', 'letter']],
    ['✎', 'Lower Right Pencil', ['pencil', 'edit', 'write']],
    ['✏', 'Pencil', ['pencil', 'edit', 'write']],
    ['✐', 'Upper Right Pencil', ['pencil', 'edit', 'write']],
    ['✑', 'White Nib', ['nib', 'pen', 'write']],
    ['✒', 'Black Nib', ['nib', 'pen', 'write']],
    ['✂', 'Black Scissors', ['scissors', 'cut', 'snip']],
    ['✃', 'Lower Blade Scissors', ['scissors', 'cut']],
    ['✄', 'White Scissors', ['scissors', 'cut', 'outline']],
    ['☀', 'Black Sun with Rays', ['sun', 'sunny', 'weather', 'bright']],
    ['☁', 'Cloud', ['cloud', 'weather', 'cloudy']],
    ['☂', 'Umbrella', ['umbrella', 'rain', 'weather']],
    ['☃', 'Snowman', ['snowman', 'winter', 'snow', 'christmas']],
    ['☄', 'Comet', ['comet', 'meteor', 'space', 'shooting star']],
    ['☎', 'Black Telephone', ['telephone', 'phone', 'call']],
    ['☏', 'White Telephone', ['telephone', 'phone', 'call', 'outline']],
    ['☠', 'Skull and Crossbones', ['skull', 'death', 'danger', 'poison', 'pirate']],
    ['☢', 'Radioactive Sign', ['radioactive', 'nuclear', 'radiation', 'danger']],
    ['☣', 'Biohazard Sign', ['biohazard', 'biological', 'danger', 'toxic']],
    ['☮', 'Peace Symbol', ['peace', 'pacifism', 'hippie']],
    ['☯', 'Yin Yang', ['yin yang', 'balance', 'tao', 'duality', 'harmony']],
    ['☸', 'Wheel of Dharma', ['dharma', 'buddhism', 'wheel', 'religion']],
    ['☹', 'White Frowning Face', ['sad', 'frown', 'unhappy']],
    ['☺', 'White Smiling Face', ['smile', 'happy', 'face', 'smiley']],
    ['☻', 'Black Smiling Face', ['smile', 'happy', 'face', 'smiley', 'filled']],
    ['☼', 'White Sun with Rays', ['sun', 'sunny', 'bright', 'outline']],
    ['☽', 'First Quarter Moon', ['moon', 'crescent', 'night']],
    ['☾', 'Last Quarter Moon', ['moon', 'crescent', 'night']],
    ['♀', 'Female Sign', ['female', 'woman', 'venus', 'gender']],
    ['♂', 'Male Sign', ['male', 'man', 'mars', 'gender']],
    ['⚥', 'Male and Female Sign', ['transgender', 'gender', 'both']],
    ['⚢', 'Doubled Female Sign', ['lesbian', 'female', 'gay']],
    ['⚣', 'Doubled Male Sign', ['gay', 'male', 'homosexual']],
    ['♠', 'Black Spade Suit', ['spade', 'cards', 'suit', 'poker']],
    ['♣', 'Black Club Suit', ['club', 'cards', 'suit', 'poker', 'clover']],
    ['♥', 'Black Heart Suit', ['heart', 'cards', 'suit', 'poker', 'love']],
    ['♦', 'Black Diamond Suit', ['diamond', 'cards', 'suit', 'poker']],
    ['♤', 'White Spade Suit', ['spade', 'cards', 'suit', 'outline']],
    ['♧', 'White Club Suit', ['club', 'cards', 'suit', 'outline']],
    ['♡', 'White Heart Suit', ['heart', 'cards', 'suit', 'outline', 'love']],
    ['♢', 'White Diamond Suit', ['diamond', 'cards', 'suit', 'outline']],
    ['♩', 'Quarter Note', ['music', 'note', 'quarter']],
    ['♪', 'Eighth Note', ['music', 'note', 'eighth']],
    ['♫', 'Beamed Eighth Notes', ['music', 'notes', 'melody']],
    ['♬', 'Beamed Sixteenth Notes', ['music', 'notes', 'melody']],
    ['♭', 'Music Flat Sign', ['flat', 'music', 'note']],
    ['♮', 'Music Natural Sign', ['natural', 'music', 'note']],
    ['♯', 'Music Sharp Sign', ['sharp', 'music', 'note', 'hashtag']],
    ['⚀', 'Die Face-1', ['dice', 'one', 'game', 'die']],
    ['⚁', 'Die Face-2', ['dice', 'two', 'game', 'die']],
    ['⚂', 'Die Face-3', ['dice', 'three', 'game', 'die']],
    ['⚃', 'Die Face-4', ['dice', 'four', 'game', 'die']],
    ['⚄', 'Die Face-5', ['dice', 'five', 'game', 'die']],
    ['⚅', 'Die Face-6', ['dice', 'six', 'game', 'die']],
    ['⚐', 'White Flag', ['flag', 'white', 'surrender']],
    ['⚑', 'Black Flag', ['flag', 'black', 'marker']],
    ['⚓', 'Anchor', ['anchor', 'ship', 'nautical', 'navy']],
    ['⚔', 'Crossed Swords', ['swords', 'battle', 'fight', 'war', 'combat']],
    ['⚖', 'Scales', ['scales', 'justice', 'balance', 'libra', 'law']],
    ['⚗', 'Alembic', ['alembic', 'chemistry', 'science', 'alchemy']],
    ['⚙', 'Gear', ['gear', 'cog', 'settings', 'mechanical']],
    ['⚛', 'Atom Symbol', ['atom', 'nuclear', 'science', 'physics']],
    ['⚜', 'Fleur-de-lis', ['fleur de lis', 'french', 'lily', 'royal']],
    ['⚡', 'High Voltage', ['lightning', 'electricity', 'power', 'flash', 'bolt']],
    ['⚪', 'White Circle', ['circle', 'white', 'dot']],
    ['⚫', 'Black Circle', ['circle', 'black', 'dot']],
    ['⚬', 'Medium Small White Circle', ['circle', 'bullet', 'small']],
    ['⚰', 'Coffin', ['coffin', 'death', 'funeral', 'casket']],
    ['⚱', 'Funeral Urn', ['urn', 'death', 'funeral', 'ashes']],
    ['⛏', 'Pick', ['pick', 'mine', 'minecraft', 'pickaxe']],
    ['⛔', 'No Entry', ['no entry', 'stop', 'forbidden', 'prohibited']],
    ['⛤', 'Pentagram', ['pentagram', 'star', 'occult']],
    ['⛧', 'Inverted Pentagram', ['pentagram', 'inverted', 'occult', 'satanic']],
    ['⛨', 'Black Cross on Shield', ['shield', 'cross', 'medical', 'hospital']],
    ['⛩', 'Shinto Shrine', ['shrine', 'torii', 'japan', 'shinto']],
    ['⛪', 'Church', ['church', 'christian', 'religion', 'building']],
    ['⛰', 'Mountain', ['mountain', 'peak', 'nature', 'hiking']],
    ['⛱', 'Umbrella on Ground', ['umbrella', 'beach', 'sun', 'vacation']],
    ['⛲', 'Fountain', ['fountain', 'water', 'park']],
    ['⛳', 'Flag in Hole', ['golf', 'flag', 'hole', 'sport']],
    ['⛴', 'Ferry', ['ferry', 'boat', 'ship', 'transport']],
    ['⛵', 'Sailboat', ['sailboat', 'boat', 'sailing', 'yacht']],
    ['⛷', 'Skier', ['ski', 'skiing', 'winter', 'sport']],
    ['⛸', 'Ice Skate', ['ice skate', 'skating', 'winter', 'sport']],
    ['⛹', 'Person Bouncing Ball', ['basketball', 'sport', 'ball']],
    ['⛺', 'Tent', ['tent', 'camping', 'outdoors', 'nature']],
    ['⛽', 'Fuel Pump', ['gas', 'fuel', 'petrol', 'station']],
    ['⛾', 'Cup on Black Square', ['cup', 'drink', 'rest stop']],
    ['✀', 'Black Safety Scissors', ['scissors', 'cut', 'craft']],
    ['✁', 'Upper Blade Scissors', ['scissors', 'cut']],

    # Box Drawing & Blocks
    ['─', 'Box Drawings Light Horizontal', ['line', 'horizontal', 'box', 'ascii']],
    ['│', 'Box Drawings Light Vertical', ['line', 'vertical', 'box', 'ascii']],
    ['┌', 'Box Drawings Light Down and Right', ['corner', 'top left', 'box', 'ascii']],
    ['┐', 'Box Drawings Light Down and Left', ['corner', 'top right', 'box', 'ascii']],
    ['└', 'Box Drawings Light Up and Right', ['corner', 'bottom left', 'box', 'ascii']],
    ['┘', 'Box Drawings Light Up and Left', ['corner', 'bottom right', 'box', 'ascii']],
    ['├', 'Box Drawings Light Vertical and Right', ['tee', 'left', 'box', 'ascii']],
    ['┤', 'Box Drawings Light Vertical and Left', ['tee', 'right', 'box', 'ascii']],
    ['┬', 'Box Drawings Light Down and Horizontal', ['tee', 'top', 'box', 'ascii']],
    ['┴', 'Box Drawings Light Up and Horizontal', ['tee', 'bottom', 'box', 'ascii']],
    ['┼', 'Box Drawings Light Vertical and Horizontal', ['cross', 'plus', 'box', 'ascii']],
    ['═', 'Box Drawings Double Horizontal', ['line', 'double', 'horizontal', 'box']],
    ['║', 'Box Drawings Double Vertical', ['line', 'double', 'vertical', 'box']],
    ['╔', 'Box Drawings Double Down and Right', ['corner', 'double', 'top left', 'box']],
    ['╗', 'Box Drawings Double Down and Left', ['corner', 'double', 'top right', 'box']],
    ['╚', 'Box Drawings Double Up and Right', ['corner', 'double', 'bottom left', 'box']],
    ['╝', 'Box Drawings Double Up and Left', ['corner', 'double', 'bottom right', 'box']],
    ['╠', 'Box Drawings Double Vertical and Right', ['tee', 'double', 'left', 'box']],
    ['╣', 'Box Drawings Double Vertical and Left', ['tee', 'double', 'right', 'box']],
    ['╦', 'Box Drawings Double Down and Horizontal', ['tee', 'double', 'top', 'box']],
    ['╩', 'Box Drawings Double Up and Horizontal', ['tee', 'double', 'bottom', 'box']],
    ['╬', 'Box Drawings Double Vertical and Horizontal', ['cross', 'double', 'box']],
    ['█', 'Full Block', ['block', 'full', 'solid', 'fill']],
    ['▀', 'Upper Half Block', ['block', 'upper', 'half']],
    ['▄', 'Lower Half Block', ['block', 'lower', 'half']],
    ['▌', 'Left Half Block', ['block', 'left', 'half']],
    ['▐', 'Right Half Block', ['block', 'right', 'half']],
    ['░', 'Light Shade', ['shade', 'light', 'pattern', 'fill']],
    ['▒', 'Medium Shade', ['shade', 'medium', 'pattern', 'fill']],
    ['▓', 'Dark Shade', ['shade', 'dark', 'pattern', 'fill']],

    # Additional Useful Symbols
    ['©', 'Copyright Sign', ['copyright', 'c', 'legal', 'intellectual property']],
    ['®', 'Registered Sign', ['registered', 'r', 'trademark', 'legal']],
    ['™', 'Trade Mark Sign', ['trademark', 'tm', 'brand', 'legal']],
    ['℠', 'Service Mark', ['service mark', 'sm', 'legal']],
    ['℡', 'Telephone Sign', ['telephone', 'tel', 'phone']],
    ['℮', 'Estimated Symbol', ['estimated', 'e-mark', 'europe']],
    ['Ⓐ', 'Circled Latin Capital Letter A', ['circled', 'a', 'anarchy']],
    ['⌘', 'Place of Interest Sign', ['command', 'cmd', 'mac', 'apple', 'key']],
    ['⌥', 'Option Key', ['option', 'alt', 'mac', 'apple', 'key']],
    ['⇧', 'Upwards White Arrow', ['shift', 'arrow', 'mac', 'key']],
    ['⌃', 'Up Arrowhead', ['control', 'ctrl', 'mac', 'key']],
    ['⎋', 'Broken Circle with Northwest Arrow', ['escape', 'esc', 'key']],
    ['⏎', 'Return Symbol', ['return', 'enter', 'key']],
    ['⌫', 'Erase to the Left', ['backspace', 'delete', 'key']],
    ['⌦', 'Erase to the Right', ['delete', 'forward delete', 'key']],
    ['⇥', 'Rightwards Arrow to Bar', ['tab', 'key', 'indent']],
    ['⇤', 'Leftwards Arrow to Bar', ['backtab', 'shift tab', 'key']],
    ['␣', 'Open Box', ['space', 'spacebar', 'key', 'blank']],
    ['⎵', 'Bottom Square Bracket', ['space', 'underscore', 'key']],
    ['⍽', 'Shouldered Open Box', ['space', 'nbsp', 'non-breaking']],
    ['⌨', 'Keyboard', ['keyboard', 'type', 'input']],
    ['⏏', 'Eject Symbol', ['eject', 'media', 'disc']],
    ['⌚', 'Watch', ['watch', 'time', 'clock']],
    ['⌛', 'Hourglass', ['hourglass', 'time', 'wait', 'loading']],
    ['⌬', 'Benzene Ring', ['benzene', 'chemistry', 'organic', 'hexagon']],
    ['⏣', 'Benzene Ring with Circle', ['benzene', 'chemistry', 'aromatic']],
    ['⎈', 'Helm Symbol', ['helm', 'control', 'steering']],
    ['⏻', 'Power Symbol', ['power', 'on off', 'standby']],
    ['⏼', 'Power On-Off Symbol', ['power', 'toggle', 'on off']],
    ['⏽', 'Power On Symbol', ['power', 'on', 'standby']],
    ['⭘', 'Power Off Symbol', ['power', 'off', 'circle']],
    ['⏾', 'Power Sleep Symbol', ['sleep', 'standby', 'power']],
    ['🜂', 'Alchemical Symbol for Fire', ['fire', 'alchemy', 'element', 'triangle']],
    ['🜃', 'Alchemical Symbol for Earth', ['earth', 'alchemy', 'element', 'triangle']],
    ['🜁', 'Alchemical Symbol for Air', ['air', 'alchemy', 'element', 'triangle']],
    ['🜄', 'Alchemical Symbol for Water', ['water', 'alchemy', 'element', 'triangle']],
);

my @results;

if ($query eq '') {
    # Show popular emojis when no query
    my @popular = ('😀', '❤️', '👍', '😂', '🎉', '✨', '🔥', '💯', '🙏', '😊');
    my %popular_set = map { $_ => 1 } @popular;
    for my $e (@emojis) {
        if ($popular_set{$e->[0]}) {
            push @results, { emoji => $e, score => 100 };
        }
    }
} else {
    my @query_terms = split /\s+/, $query;

    for my $e (@emojis) {
        # Merge custom keywords if they exist for this emoji
        my @keywords = @{$e->[2]};
        if (exists $custom_keywords{$e->[0]}) {
            push @keywords, @{$custom_keywords{$e->[0]}};
        }
        my $emoji_with_custom = [$e->[0], $e->[1], \@keywords];

        my $score = calculate_score($emoji_with_custom, $query, \@query_terms);
        if ($score > 0) {
            push @results, { emoji => $emoji_with_custom, score => $score, type => 'emoji' };
        }
    }

    # Also search unicode characters if enabled
    if ($settings{unicode_enabled}) {
        for my $u (@unicode_chars) {
            my @keywords = @{$u->[2]};
            if (exists $custom_keywords{$u->[0]}) {
                push @keywords, @{$custom_keywords{$u->[0]}};
            }
            my $unicode_with_custom = [$u->[0], $u->[1], \@keywords];

            my $score = calculate_score($unicode_with_custom, $query, \@query_terms);
            if ($score > 0) {
                push @results, { emoji => $unicode_with_custom, score => $score, type => 'unicode' };
            }
        }
    }

    @results = sort { $b->{score} <=> $a->{score} } @results;
}

my @items;
my $count = 0;
for my $r (@results) {
    last if $count >= 50;
    my $e = $r->{emoji};
    my $type = $r->{type} // 'emoji';
    my $keywords_preview = join(', ', @{$e->[2]}[0..2]);
    my $subtitle = $type eq 'unicode' ? "Unicode · $keywords_preview" : $keywords_preview;
    push @items, {
        uid => $e->[0],
        title => "$e->[0]  $e->[1]",
        subtitle => $subtitle,
        arg => $e->[0],
        text => {
            copy => $e->[0],
            largetype => $e->[0]
        },
        mods => {
            cmd => {
                valid => JSON::PP::true,
                arg => $e->[0],
                subtitle => "Paste directly into frontmost app"
            }
        }
    };
    $count++;
}

if (@items == 0) {
    my $unicode_hint = $settings{unicode_enabled} ? "" : " (Unicode search disabled)";
    push @items, {
        title => "No results found",
        subtitle => "No matches for '$query'$unicode_hint",
        valid => JSON::PP::false
    };
}

my $output = { items => \@items };
print encode_json($output) . "\n";

sub calculate_score {
    my ($emoji, $query, $query_terms) = @_;
    my $score = 0;
    my $name_lower = lc($emoji->[1]);

    # Exact name match - highest priority
    $score += 1000 if $name_lower eq $query;

    # Name starts with query
    $score += 500 if index($name_lower, $query) == 0;

    # Name contains query
    $score += 200 if index($name_lower, $query) >= 0;

    # Check keywords
    for my $keyword (@{$emoji->[2]}) {
        my $keyword_lower = lc($keyword);

        # Exact keyword match
        $score += 300 if $keyword_lower eq $query;

        # Keyword starts with query
        $score += 150 if index($keyword_lower, $query) == 0;

        # Keyword contains query
        $score += 50 if index($keyword_lower, $query) >= 0;

        # Check each query term
        for my $term (@$query_terms) {
            $score += 30 if index($keyword_lower, $term) >= 0;
            $score += 10 if fuzzy_match($keyword_lower, $term);
        }
    }

    return $score;
}

sub fuzzy_match {
    my ($str, $pattern) = @_;
    return 1 if length($pattern) == 0;
    return 0 if length($str) == 0;

    my $pattern_idx = 0;
    for my $char (split //, $str) {
        if ($pattern_idx < length($pattern) && lc($char) eq lc(substr($pattern, $pattern_idx, 1))) {
            $pattern_idx++;
        }
    }
    return $pattern_idx == length($pattern);
}
