package main

func getEmojiDatabase() []Emoji {
	return []Emoji{
		// Smileys & Emotion
		{"😀", "Grinning Face", []string{"happy", "smile", "joy", "cheerful", "glad", "pleased", "delighted"}},
		{"😃", "Grinning Face with Big Eyes", []string{"happy", "smile", "joy", "excited", "eager"}},
		{"😄", "Grinning Face with Smiling Eyes", []string{"happy", "smile", "joy", "laugh", "pleased"}},
		{"😁", "Beaming Face", []string{"happy", "smile", "grin", "excited", "cheerful"}},
		{"😅", "Grinning Face with Sweat", []string{"nervous", "awkward", "relief", "phew", "sweat"}},
		{"😂", "Face with Tears of Joy", []string{"laugh", "funny", "hilarious", "lol", "lmao", "crying laughing", "haha"}},
		{"🤣", "Rolling on the Floor Laughing", []string{"laugh", "funny", "hilarious", "rofl", "lmao"}},
		{"😊", "Smiling Face with Smiling Eyes", []string{"happy", "blush", "pleased", "content", "warm"}},
		{"😇", "Smiling Face with Halo", []string{"angel", "innocent", "blessed", "holy", "good"}},
		{"🙂", "Slightly Smiling Face", []string{"okay", "fine", "subtle", "mild", "pleasant"}},
		{"🙃", "Upside-Down Face", []string{"sarcasm", "silly", "irony", "goofy", "playful"}},
		{"😉", "Winking Face", []string{"wink", "flirt", "joke", "playful", "hint"}},
		{"😌", "Relieved Face", []string{"relieved", "peaceful", "calm", "content", "relaxed"}},
		{"😍", "Smiling Face with Heart-Eyes", []string{"love", "crush", "adore", "infatuation", "heart eyes"}},
		{"🥰", "Smiling Face with Hearts", []string{"love", "affection", "adore", "grateful", "blessed"}},
		{"😘", "Face Blowing a Kiss", []string{"kiss", "love", "flirt", "romantic", "mwah"}},
		{"😗", "Kissing Face", []string{"kiss", "whistle", "smooch"}},
		{"😙", "Kissing Face with Smiling Eyes", []string{"kiss", "affection", "happy kiss"}},
		{"😚", "Kissing Face with Closed Eyes", []string{"kiss", "love", "affection", "peck"}},
		{"😋", "Face Savoring Food", []string{"yummy", "delicious", "tasty", "food", "hungry"}},
		{"😛", "Face with Tongue", []string{"tongue", "playful", "silly", "tease", "bleh"}},
		{"😜", "Winking Face with Tongue", []string{"tongue", "wink", "playful", "silly", "crazy"}},
		{"🤪", "Zany Face", []string{"crazy", "wild", "goofy", "silly", "wacky"}},
		{"😝", "Squinting Face with Tongue", []string{"tongue", "playful", "silly", "gross", "eww"}},
		{"🤑", "Money-Mouth Face", []string{"money", "rich", "dollar", "wealth", "greedy", "cash"}},
		{"🤗", "Hugging Face", []string{"hug", "embrace", "warm", "friendly", "welcoming"}},
		{"🤭", "Face with Hand Over Mouth", []string{"oops", "giggle", "shy", "secret", "tee-hee"}},
		{"🤫", "Shushing Face", []string{"quiet", "shush", "secret", "silence", "hush"}},
		{"🤔", "Thinking Face", []string{"think", "hmm", "wonder", "consider", "ponder", "curious"}},
		{"🤐", "Zipper-Mouth Face", []string{"secret", "quiet", "mute", "lips sealed", "confidential"}},
		{"🤨", "Face with Raised Eyebrow", []string{"skeptical", "suspicious", "doubt", "really", "hmm"}},
		{"😐", "Neutral Face", []string{"neutral", "meh", "indifferent", "blank", "expressionless"}},
		{"😑", "Expressionless Face", []string{"blank", "meh", "unimpressed", "deadpan"}},
		{"😶", "Face Without Mouth", []string{"speechless", "silent", "mute", "no comment"}},
		{"😏", "Smirking Face", []string{"smirk", "smug", "flirt", "suggestive", "sly"}},
		{"😒", "Unamused Face", []string{"unamused", "annoyed", "bored", "meh", "whatever"}},
		{"🙄", "Face with Rolling Eyes", []string{"eye roll", "annoyed", "frustrated", "whatever", "duh"}},
		{"😬", "Grimacing Face", []string{"awkward", "nervous", "tense", "cringe", "yikes"}},
		{"😮‍💨", "Face Exhaling", []string{"sigh", "relief", "exhale", "tired", "phew"}},
		{"🤥", "Lying Face", []string{"lie", "pinocchio", "dishonest", "fib"}},
		{"😌", "Relieved Face", []string{"relieved", "peaceful", "calm", "zen"}},
		{"😔", "Pensive Face", []string{"sad", "pensive", "disappointed", "reflective"}},
		{"😪", "Sleepy Face", []string{"sleepy", "tired", "drowsy", "exhausted"}},
		{"🤤", "Drooling Face", []string{"drool", "hungry", "desire", "want", "yummy"}},
		{"😴", "Sleeping Face", []string{"sleep", "tired", "zzz", "nap", "rest", "snore"}},
		{"😷", "Face with Medical Mask", []string{"sick", "mask", "ill", "covid", "medical", "health"}},
		{"🤒", "Face with Thermometer", []string{"sick", "fever", "ill", "temperature", "unwell"}},
		{"🤕", "Face with Head-Bandage", []string{"hurt", "injured", "bandage", "pain", "accident"}},
		{"🤢", "Nauseated Face", []string{"sick", "nausea", "gross", "disgusted", "queasy", "vomit"}},
		{"🤮", "Face Vomiting", []string{"vomit", "sick", "puke", "gross", "disgusting"}},
		{"🤧", "Sneezing Face", []string{"sneeze", "sick", "cold", "allergies", "achoo"}},
		{"🥵", "Hot Face", []string{"hot", "heat", "sweating", "warm", "temperature"}},
		{"🥶", "Cold Face", []string{"cold", "freezing", "frozen", "ice", "chilly"}},
		{"🥴", "Woozy Face", []string{"drunk", "dizzy", "woozy", "tipsy", "intoxicated"}},
		{"😵", "Face with Crossed-Out Eyes", []string{"dizzy", "dead", "shocked", "overwhelmed"}},
		{"😵‍💫", "Face with Spiral Eyes", []string{"dizzy", "hypnotized", "disoriented", "confused"}},
		{"🤯", "Exploding Head", []string{"mind blown", "shocked", "amazed", "wow", "unbelievable"}},
		{"🤠", "Cowboy Hat Face", []string{"cowboy", "western", "yeehaw", "country", "hat"}},
		{"🥳", "Partying Face", []string{"party", "celebrate", "birthday", "fun", "festive", "congratulations"}},
		{"🥸", "Disguised Face", []string{"disguise", "incognito", "hidden", "spy", "glasses"}},
		{"😎", "Smiling Face with Sunglasses", []string{"cool", "sunglasses", "awesome", "confident", "chill"}},
		{"🤓", "Nerd Face", []string{"nerd", "geek", "smart", "glasses", "studious"}},
		{"🧐", "Face with Monocle", []string{"fancy", "curious", "investigate", "inspect", "hmm"}},
		{"😕", "Confused Face", []string{"confused", "puzzled", "unsure", "uncertain"}},
		{"😟", "Worried Face", []string{"worried", "concerned", "anxious", "nervous"}},
		{"🙁", "Slightly Frowning Face", []string{"sad", "frown", "disappointed", "unhappy"}},
		{"☹️", "Frowning Face", []string{"sad", "frown", "unhappy", "disappointed"}},
		{"😮", "Face with Open Mouth", []string{"surprised", "wow", "shocked", "amazed"}},
		{"😯", "Hushed Face", []string{"surprised", "stunned", "speechless", "wow"}},
		{"😲", "Astonished Face", []string{"astonished", "shocked", "amazed", "wow", "omg"}},
		{"😳", "Flushed Face", []string{"embarrassed", "flushed", "shy", "awkward", "blush"}},
		{"🥺", "Pleading Face", []string{"please", "puppy eyes", "beg", "cute", "sad", "uwu"}},
		{"😦", "Frowning Face with Open Mouth", []string{"sad", "shocked", "disappointed"}},
		{"😧", "Anguished Face", []string{"anguish", "shocked", "horrified", "distressed"}},
		{"😨", "Fearful Face", []string{"fear", "scared", "afraid", "terrified", "shock"}},
		{"😰", "Anxious Face with Sweat", []string{"anxious", "nervous", "worried", "stressed", "sweat"}},
		{"😥", "Sad but Relieved Face", []string{"sad", "relieved", "disappointed", "sweat"}},
		{"😢", "Crying Face", []string{"cry", "sad", "tear", "unhappy", "upset"}},
		{"😭", "Loudly Crying Face", []string{"cry", "sobbing", "sad", "tears", "bawling", "wailing"}},
		{"😱", "Face Screaming in Fear", []string{"scream", "fear", "horror", "shocked", "scared", "omg"}},
		{"😖", "Confounded Face", []string{"frustrated", "confused", "upset", "stressed"}},
		{"😣", "Persevering Face", []string{"struggle", "frustrated", "trying", "effort"}},
		{"😞", "Disappointed Face", []string{"disappointed", "sad", "let down", "unhappy"}},
		{"😓", "Downcast Face with Sweat", []string{"disappointed", "sad", "sweat", "hard work"}},
		{"😩", "Weary Face", []string{"tired", "weary", "frustrated", "exhausted", "fed up"}},
		{"😫", "Tired Face", []string{"tired", "exhausted", "frustrated", "sleepy"}},
		{"🥱", "Yawning Face", []string{"yawn", "tired", "sleepy", "bored", "boring"}},
		{"😤", "Face with Steam From Nose", []string{"angry", "frustrated", "triumph", "huffing"}},
		{"😡", "Pouting Face", []string{"angry", "mad", "furious", "rage", "pout"}},
		{"😠", "Angry Face", []string{"angry", "mad", "annoyed", "grumpy"}},
		{"🤬", "Face with Symbols on Mouth", []string{"swear", "curse", "angry", "censored", "expletive"}},
		{"😈", "Smiling Face with Horns", []string{"devil", "evil", "mischief", "naughty", "trouble"}},
		{"👿", "Angry Face with Horns", []string{"devil", "angry", "evil", "imp"}},
		{"💀", "Skull", []string{"dead", "death", "skeleton", "scary", "halloween", "rip"}},
		{"☠️", "Skull and Crossbones", []string{"death", "danger", "poison", "pirate", "toxic"}},
		{"💩", "Pile of Poo", []string{"poop", "crap", "shit", "funny", "gross"}},
		{"🤡", "Clown Face", []string{"clown", "fool", "circus", "funny", "joke"}},
		{"👹", "Ogre", []string{"monster", "scary", "japanese", "oni", "demon"}},
		{"👺", "Goblin", []string{"monster", "japanese", "tengu", "demon"}},
		{"👻", "Ghost", []string{"ghost", "halloween", "spooky", "scary", "boo"}},
		{"👽", "Alien", []string{"alien", "ufo", "space", "extraterrestrial", "et"}},
		{"👾", "Alien Monster", []string{"alien", "game", "space invaders", "pixel", "arcade"}},
		{"🤖", "Robot", []string{"robot", "bot", "machine", "ai", "android", "technology"}},
		{"😺", "Smiling Cat", []string{"cat", "happy", "smile", "pet"}},
		{"😸", "Grinning Cat", []string{"cat", "happy", "grin", "pet"}},
		{"😹", "Cat with Tears of Joy", []string{"cat", "laugh", "funny", "pet"}},
		{"😻", "Smiling Cat with Heart-Eyes", []string{"cat", "love", "heart eyes", "pet"}},
		{"😼", "Cat with Wry Smile", []string{"cat", "smirk", "sly", "pet"}},
		{"😽", "Kissing Cat", []string{"cat", "kiss", "love", "pet"}},
		{"🙀", "Weary Cat", []string{"cat", "shocked", "scared", "pet"}},
		{"😿", "Crying Cat", []string{"cat", "sad", "cry", "pet"}},
		{"😾", "Pouting Cat", []string{"cat", "angry", "grumpy", "pet"}},
		{"🙈", "See-No-Evil Monkey", []string{"monkey", "hide", "shy", "embarrassed", "don't look"}},
		{"🙉", "Hear-No-Evil Monkey", []string{"monkey", "ignore", "not listening", "la la la"}},
		{"🙊", "Speak-No-Evil Monkey", []string{"monkey", "secret", "oops", "quiet", "shh"}},

		// Gestures & Body Parts
		{"👋", "Waving Hand", []string{"wave", "hello", "hi", "bye", "goodbye", "greeting"}},
		{"🤚", "Raised Back of Hand", []string{"hand", "stop", "high five"}},
		{"🖐️", "Hand with Fingers Splayed", []string{"hand", "five", "stop", "high five"}},
		{"✋", "Raised Hand", []string{"hand", "stop", "high five", "halt"}},
		{"🖖", "Vulcan Salute", []string{"spock", "star trek", "live long", "prosper"}},
		{"👌", "OK Hand", []string{"ok", "okay", "perfect", "good", "nice", "fine"}},
		{"🤌", "Pinched Fingers", []string{"italian", "perfection", "chef kiss", "what do you want"}},
		{"🤏", "Pinching Hand", []string{"small", "tiny", "little", "pinch", "bit"}},
		{"✌️", "Victory Hand", []string{"peace", "victory", "two", "v sign"}},
		{"🤞", "Crossed Fingers", []string{"luck", "hope", "fingers crossed", "wish"}},
		{"🤟", "Love-You Gesture", []string{"love", "ily", "rock", "sign language"}},
		{"🤘", "Sign of the Horns", []string{"rock", "metal", "horns", "rock on", "party"}},
		{"🤙", "Call Me Hand", []string{"call", "shaka", "hang loose", "phone", "surf"}},
		{"👈", "Backhand Index Pointing Left", []string{"point", "left", "direction", "that way"}},
		{"👉", "Backhand Index Pointing Right", []string{"point", "right", "direction", "this way"}},
		{"👆", "Backhand Index Pointing Up", []string{"point", "up", "direction", "above"}},
		{"🖕", "Middle Finger", []string{"middle finger", "fuck", "flip off", "rude", "angry"}},
		{"👇", "Backhand Index Pointing Down", []string{"point", "down", "direction", "below"}},
		{"☝️", "Index Pointing Up", []string{"point", "up", "one", "wait", "important"}},
		{"👍", "Thumbs Up", []string{"good", "yes", "ok", "approve", "like", "agree", "nice"}},
		{"👎", "Thumbs Down", []string{"bad", "no", "dislike", "disapprove", "disagree", "boo"}},
		{"✊", "Raised Fist", []string{"fist", "power", "solidarity", "punch", "strong"}},
		{"👊", "Oncoming Fist", []string{"fist bump", "punch", "bro", "power"}},
		{"🤛", "Left-Facing Fist", []string{"fist bump", "punch", "left"}},
		{"🤜", "Right-Facing Fist", []string{"fist bump", "punch", "right"}},
		{"👏", "Clapping Hands", []string{"clap", "applause", "bravo", "congratulations", "well done"}},
		{"🙌", "Raising Hands", []string{"celebrate", "praise", "hooray", "yay", "hallelujah"}},
		{"👐", "Open Hands", []string{"open", "hands", "hug", "jazz hands"}},
		{"🤲", "Palms Up Together", []string{"prayer", "please", "give", "receive"}},
		{"🤝", "Handshake", []string{"handshake", "deal", "agreement", "meeting", "partnership"}},
		{"🙏", "Folded Hands", []string{"pray", "please", "thank you", "hope", "namaste", "grateful"}},
		{"✍️", "Writing Hand", []string{"write", "writing", "sign", "signature"}},
		{"💅", "Nail Polish", []string{"nails", "beauty", "fabulous", "sassy", "glamour"}},
		{"🤳", "Selfie", []string{"selfie", "photo", "camera", "phone", "picture"}},
		{"💪", "Flexed Biceps", []string{"strong", "muscle", "power", "strength", "gym", "workout", "flex"}},
		{"🦾", "Mechanical Arm", []string{"robot", "prosthetic", "strong", "cyborg"}},
		{"🦿", "Mechanical Leg", []string{"robot", "prosthetic", "cyborg"}},
		{"🦵", "Leg", []string{"leg", "kick", "limb"}},
		{"🦶", "Foot", []string{"foot", "kick", "stomp"}},
		{"👂", "Ear", []string{"ear", "hear", "listen", "sound"}},
		{"🦻", "Ear with Hearing Aid", []string{"deaf", "hearing aid", "accessibility"}},
		{"👃", "Nose", []string{"nose", "smell", "sniff"}},
		{"🧠", "Brain", []string{"brain", "smart", "think", "intelligence", "mind"}},
		{"👀", "Eyes", []string{"eyes", "look", "see", "watch", "stare", "looking"}},
		{"👁️", "Eye", []string{"eye", "see", "look", "watch"}},
		{"👅", "Tongue", []string{"tongue", "taste", "lick"}},
		{"👄", "Mouth", []string{"mouth", "lips", "kiss"}},

		// Hearts & Love
		{"💋", "Kiss Mark", []string{"kiss", "lips", "love", "lipstick", "smooch"}},
		{"❤️", "Red Heart", []string{"love", "heart", "romance", "like", "favorite"}},
		{"🧡", "Orange Heart", []string{"love", "heart", "orange", "friendship"}},
		{"💛", "Yellow Heart", []string{"love", "heart", "yellow", "friendship", "happiness"}},
		{"💚", "Green Heart", []string{"love", "heart", "green", "nature", "jealousy"}},
		{"💙", "Blue Heart", []string{"love", "heart", "blue", "trust", "loyalty"}},
		{"💜", "Purple Heart", []string{"love", "heart", "purple", "sensitive", "bts"}},
		{"🖤", "Black Heart", []string{"love", "heart", "black", "dark", "emo", "goth"}},
		{"🤍", "White Heart", []string{"love", "heart", "white", "pure", "clean"}},
		{"🤎", "Brown Heart", []string{"love", "heart", "brown", "nature"}},
		{"💔", "Broken Heart", []string{"heartbreak", "sad", "breakup", "hurt", "pain"}},
		{"❤️‍🔥", "Heart on Fire", []string{"love", "passion", "lust", "burning", "desire"}},
		{"❤️‍🩹", "Mending Heart", []string{"healing", "recovery", "getting better", "health"}},
		{"❣️", "Heart Exclamation", []string{"love", "heart", "exclamation", "emphasis"}},
		{"💕", "Two Hearts", []string{"love", "hearts", "romance", "couple"}},
		{"💞", "Revolving Hearts", []string{"love", "hearts", "romance", "falling in love"}},
		{"💓", "Beating Heart", []string{"love", "heartbeat", "alive", "excited"}},
		{"💗", "Growing Heart", []string{"love", "heart", "growing", "affection"}},
		{"💖", "Sparkling Heart", []string{"love", "heart", "sparkle", "excited", "shiny"}},
		{"💘", "Heart with Arrow", []string{"love", "cupid", "romance", "valentine"}},
		{"💝", "Heart with Ribbon", []string{"love", "gift", "present", "valentine"}},
		{"💟", "Heart Decoration", []string{"love", "heart", "decoration"}},

		// Celebrations & Objects
		{"🎉", "Party Popper", []string{"party", "celebrate", "congratulations", "birthday", "new year", "confetti"}},
		{"🎊", "Confetti Ball", []string{"party", "celebrate", "confetti", "festive"}},
		{"🎈", "Balloon", []string{"party", "balloon", "birthday", "celebration"}},
		{"🎁", "Wrapped Gift", []string{"gift", "present", "birthday", "christmas", "surprise"}},
		{"🎂", "Birthday Cake", []string{"birthday", "cake", "celebration", "party"}},
		{"🎄", "Christmas Tree", []string{"christmas", "tree", "holiday", "xmas", "december"}},
		{"🎃", "Jack-O-Lantern", []string{"halloween", "pumpkin", "spooky", "october"}},
		{"🎆", "Fireworks", []string{"fireworks", "celebration", "new year", "july 4th"}},
		{"🎇", "Sparkler", []string{"sparkler", "fireworks", "celebration"}},
		{"✨", "Sparkles", []string{"sparkle", "shine", "magic", "special", "clean", "new", "star"}},
		{"🎀", "Ribbon", []string{"ribbon", "gift", "present", "bow", "cute"}},
		{"🏆", "Trophy", []string{"trophy", "winner", "award", "champion", "first place", "success"}},
		{"🥇", "1st Place Medal", []string{"gold", "first", "winner", "medal", "champion"}},
		{"🥈", "2nd Place Medal", []string{"silver", "second", "medal", "runner up"}},
		{"🥉", "3rd Place Medal", []string{"bronze", "third", "medal"}},
		{"🏅", "Sports Medal", []string{"medal", "sports", "winner", "achievement"}},
		{"🎖️", "Military Medal", []string{"medal", "military", "honor", "award"}},

		// Weather & Nature
		{"☀️", "Sun", []string{"sun", "sunny", "weather", "hot", "summer", "bright"}},
		{"🌙", "Crescent Moon", []string{"moon", "night", "sleep", "dark", "crescent"}},
		{"⭐", "Star", []string{"star", "favorite", "rating", "sky", "night"}},
		{"🌟", "Glowing Star", []string{"star", "glow", "sparkle", "shiny", "special"}},
		{"💫", "Dizzy", []string{"dizzy", "star", "shooting star", "sparkle"}},
		{"🌈", "Rainbow", []string{"rainbow", "colorful", "pride", "lgbtq", "colors"}},
		{"☁️", "Cloud", []string{"cloud", "weather", "sky", "cloudy"}},
		{"⛈️", "Cloud with Lightning and Rain", []string{"storm", "thunder", "lightning", "rain", "weather"}},
		{"🌧️", "Cloud with Rain", []string{"rain", "rainy", "weather", "cloud"}},
		{"❄️", "Snowflake", []string{"snow", "cold", "winter", "frozen", "ice"}},
		{"🔥", "Fire", []string{"fire", "hot", "lit", "flame", "burn", "awesome", "trending"}},
		{"💧", "Droplet", []string{"water", "drop", "rain", "tear", "sweat"}},
		{"🌊", "Water Wave", []string{"wave", "ocean", "sea", "water", "surf", "beach"}},

		// Plants
		{"🌸", "Cherry Blossom", []string{"flower", "cherry", "blossom", "spring", "pink", "japan"}},
		{"🌺", "Hibiscus", []string{"flower", "tropical", "hawaii", "pink"}},
		{"🌻", "Sunflower", []string{"flower", "sunflower", "yellow", "summer", "sun"}},
		{"🌹", "Rose", []string{"flower", "rose", "love", "romance", "red", "valentine"}},
		{"🌷", "Tulip", []string{"flower", "tulip", "spring", "pink"}},
		{"🌱", "Seedling", []string{"plant", "seedling", "growth", "new", "sprout", "garden"}},
		{"🌲", "Evergreen Tree", []string{"tree", "evergreen", "pine", "forest", "nature"}},
		{"🌳", "Deciduous Tree", []string{"tree", "nature", "forest", "green"}},
		{"🌴", "Palm Tree", []string{"palm", "tree", "tropical", "beach", "vacation"}},
		{"🌵", "Cactus", []string{"cactus", "desert", "plant", "succulent"}},
		{"🍀", "Four Leaf Clover", []string{"clover", "luck", "lucky", "irish", "st patrick"}},
		{"🍁", "Maple Leaf", []string{"maple", "leaf", "fall", "autumn", "canada"}},
		{"🍂", "Fallen Leaf", []string{"leaf", "fall", "autumn", "nature"}},
		{"🍃", "Leaf Fluttering in Wind", []string{"leaf", "wind", "nature", "green"}},

		// Animals
		{"🐶", "Dog Face", []string{"dog", "puppy", "pet", "cute", "animal"}},
		{"🐱", "Cat Face", []string{"cat", "kitty", "pet", "cute", "animal", "meow"}},
		{"🐭", "Mouse Face", []string{"mouse", "animal", "cute", "rodent"}},
		{"🐹", "Hamster", []string{"hamster", "pet", "cute", "rodent"}},
		{"🐰", "Rabbit Face", []string{"rabbit", "bunny", "pet", "cute", "easter"}},
		{"🦊", "Fox", []string{"fox", "animal", "clever", "cute"}},
		{"🐻", "Bear", []string{"bear", "animal", "cute", "teddy"}},
		{"🐼", "Panda", []string{"panda", "bear", "animal", "cute", "china"}},
		{"🐨", "Koala", []string{"koala", "animal", "cute", "australia"}},
		{"🐯", "Tiger Face", []string{"tiger", "animal", "cat", "wild"}},
		{"🦁", "Lion", []string{"lion", "animal", "king", "wild", "cat"}},
		{"🐮", "Cow Face", []string{"cow", "animal", "farm", "moo"}},
		{"🐷", "Pig Face", []string{"pig", "animal", "farm", "oink"}},
		{"🐸", "Frog", []string{"frog", "animal", "amphibian", "pepe"}},
		{"🐵", "Monkey Face", []string{"monkey", "animal", "ape", "primate"}},
		{"🐔", "Chicken", []string{"chicken", "animal", "bird", "farm"}},
		{"🐧", "Penguin", []string{"penguin", "animal", "bird", "cold", "linux"}},
		{"🐦", "Bird", []string{"bird", "animal", "fly", "tweet"}},
		{"🦅", "Eagle", []string{"eagle", "bird", "america", "freedom"}},
		{"🦆", "Duck", []string{"duck", "bird", "animal", "quack"}},
		{"🦉", "Owl", []string{"owl", "bird", "wise", "night"}},
		{"🐺", "Wolf", []string{"wolf", "animal", "wild", "howl"}},
		{"🐗", "Boar", []string{"boar", "pig", "wild", "animal"}},
		{"🐴", "Horse Face", []string{"horse", "animal", "pony"}},
		{"🦄", "Unicorn", []string{"unicorn", "magic", "fantasy", "mythical", "horse"}},
		{"🐝", "Bee", []string{"bee", "insect", "honey", "buzz"}},
		{"🐛", "Bug", []string{"bug", "insect", "caterpillar"}},
		{"🦋", "Butterfly", []string{"butterfly", "insect", "pretty", "nature"}},
		{"🐌", "Snail", []string{"snail", "slow", "animal"}},
		{"🐙", "Octopus", []string{"octopus", "sea", "ocean", "tentacles"}},
		{"🦀", "Crab", []string{"crab", "sea", "ocean", "zodiac", "cancer"}},
		{"🐠", "Tropical Fish", []string{"fish", "tropical", "ocean", "sea"}},
		{"🐟", "Fish", []string{"fish", "ocean", "sea", "animal"}},
		{"🐬", "Dolphin", []string{"dolphin", "ocean", "sea", "smart", "flipper"}},
		{"🐳", "Spouting Whale", []string{"whale", "ocean", "sea", "big"}},
		{"🦈", "Shark", []string{"shark", "ocean", "dangerous", "jaws"}},
		{"🐊", "Crocodile", []string{"crocodile", "alligator", "reptile"}},
		{"🐢", "Turtle", []string{"turtle", "slow", "reptile", "shell"}},
		{"🦎", "Lizard", []string{"lizard", "reptile", "gecko"}},
		{"🐍", "Snake", []string{"snake", "reptile", "slither"}},
		{"🦖", "T-Rex", []string{"dinosaur", "t-rex", "jurassic", "extinct"}},
		{"🦕", "Sauropod", []string{"dinosaur", "long neck", "jurassic", "extinct"}},

		// Food & Drink
		{"🍎", "Red Apple", []string{"apple", "fruit", "healthy", "red", "teacher"}},
		{"🍊", "Tangerine", []string{"orange", "fruit", "citrus"}},
		{"🍋", "Lemon", []string{"lemon", "fruit", "citrus", "sour", "yellow"}},
		{"🍌", "Banana", []string{"banana", "fruit", "yellow"}},
		{"🍉", "Watermelon", []string{"watermelon", "fruit", "summer"}},
		{"🍇", "Grapes", []string{"grapes", "fruit", "wine", "purple"}},
		{"🍓", "Strawberry", []string{"strawberry", "fruit", "berry", "red"}},
		{"🍑", "Peach", []string{"peach", "fruit", "butt", "booty"}},
		{"🍒", "Cherries", []string{"cherry", "cherries", "fruit", "red"}},
		{"🥑", "Avocado", []string{"avocado", "fruit", "guacamole", "healthy", "millennial"}},
		{"🥕", "Carrot", []string{"carrot", "vegetable", "orange", "healthy"}},
		{"🌽", "Ear of Corn", []string{"corn", "vegetable", "cob"}},
		{"🌶️", "Hot Pepper", []string{"pepper", "hot", "spicy", "chili"}},
		{"🥒", "Cucumber", []string{"cucumber", "vegetable", "pickle"}},
		{"🥬", "Leafy Green", []string{"lettuce", "salad", "vegetable", "healthy", "green"}},
		{"🥦", "Broccoli", []string{"broccoli", "vegetable", "healthy", "green"}},
		{"🍄", "Mushroom", []string{"mushroom", "fungus", "toadstool"}},
		{"🥜", "Peanuts", []string{"peanut", "nut", "legume"}},
		{"🍞", "Bread", []string{"bread", "toast", "loaf", "carbs"}},
		{"🥐", "Croissant", []string{"croissant", "bread", "french", "pastry"}},
		{"🥖", "Baguette Bread", []string{"baguette", "bread", "french"}},
		{"🧀", "Cheese Wedge", []string{"cheese", "dairy", "cheddar"}},
		{"🍳", "Cooking", []string{"egg", "cooking", "breakfast", "fried"}},
		{"🥞", "Pancakes", []string{"pancakes", "breakfast", "syrup"}},
		{"🥓", "Bacon", []string{"bacon", "meat", "breakfast", "pork"}},
		{"🍔", "Hamburger", []string{"burger", "hamburger", "fast food", "beef"}},
		{"🍟", "French Fries", []string{"fries", "french fries", "fast food", "potato"}},
		{"🍕", "Pizza", []string{"pizza", "italian", "fast food", "slice"}},
		{"🌭", "Hot Dog", []string{"hot dog", "sausage", "fast food"}},
		{"🥪", "Sandwich", []string{"sandwich", "lunch", "bread"}},
		{"🌮", "Taco", []string{"taco", "mexican", "food", "tuesday"}},
		{"🌯", "Burrito", []string{"burrito", "mexican", "wrap"}},
		{"🍜", "Steaming Bowl", []string{"noodles", "ramen", "soup", "asian", "pho"}},
		{"🍝", "Spaghetti", []string{"spaghetti", "pasta", "italian", "noodles"}},
		{"🍣", "Sushi", []string{"sushi", "japanese", "fish", "rice"}},
		{"🍤", "Fried Shrimp", []string{"shrimp", "tempura", "seafood"}},
		{"🍦", "Soft Ice Cream", []string{"ice cream", "dessert", "sweet", "cone"}},
		{"🍩", "Doughnut", []string{"donut", "doughnut", "dessert", "sweet"}},
		{"🍪", "Cookie", []string{"cookie", "dessert", "sweet", "biscuit"}},
		{"🎂", "Birthday Cake", []string{"cake", "birthday", "dessert", "celebration"}},
		{"🍰", "Shortcake", []string{"cake", "dessert", "strawberry", "sweet"}},
		{"🧁", "Cupcake", []string{"cupcake", "dessert", "sweet", "muffin"}},
		{"🍫", "Chocolate Bar", []string{"chocolate", "candy", "sweet", "dessert"}},
		{"🍬", "Candy", []string{"candy", "sweet", "sugar"}},
		{"🍭", "Lollipop", []string{"lollipop", "candy", "sweet"}},
		{"☕", "Hot Beverage", []string{"coffee", "tea", "hot", "drink", "cafe", "morning"}},
		{"🍵", "Teacup", []string{"tea", "green tea", "hot", "drink", "japanese"}},
		{"🍺", "Beer Mug", []string{"beer", "drink", "alcohol", "cheers"}},
		{"🍻", "Clinking Beer Mugs", []string{"beer", "cheers", "drink", "alcohol", "toast"}},
		{"🥂", "Clinking Glasses", []string{"champagne", "cheers", "toast", "celebration", "wine"}},
		{"🍷", "Wine Glass", []string{"wine", "drink", "alcohol", "red wine"}},
		{"🍸", "Cocktail Glass", []string{"cocktail", "martini", "drink", "alcohol"}},
		{"🍹", "Tropical Drink", []string{"cocktail", "tropical", "drink", "vacation"}},
		{"🧃", "Beverage Box", []string{"juice", "juice box", "drink"}},
		{"🧋", "Bubble Tea", []string{"boba", "bubble tea", "drink", "taiwanese"}},

		// Activities & Sports
		{"⚽", "Soccer Ball", []string{"soccer", "football", "ball", "sport"}},
		{"🏀", "Basketball", []string{"basketball", "ball", "sport", "nba"}},
		{"🏈", "American Football", []string{"football", "american", "sport", "nfl"}},
		{"⚾", "Baseball", []string{"baseball", "ball", "sport", "mlb"}},
		{"🎾", "Tennis", []string{"tennis", "ball", "sport", "racket"}},
		{"🏐", "Volleyball", []string{"volleyball", "ball", "sport", "beach"}},
		{"🏉", "Rugby Football", []string{"rugby", "ball", "sport"}},
		{"🎱", "Pool 8 Ball", []string{"pool", "billiards", "8 ball", "game"}},
		{"🏓", "Ping Pong", []string{"ping pong", "table tennis", "sport"}},
		{"🏸", "Badminton", []string{"badminton", "shuttlecock", "sport"}},
		{"🥊", "Boxing Glove", []string{"boxing", "fight", "sport", "punch"}},
		{"🥋", "Martial Arts Uniform", []string{"martial arts", "karate", "judo", "taekwondo"}},
		{"⛳", "Flag in Hole", []string{"golf", "sport", "hole"}},
		{"⛷️", "Skier", []string{"ski", "skiing", "winter", "sport", "snow"}},
		{"🏂", "Snowboarder", []string{"snowboard", "winter", "sport", "snow"}},
		{"🏄", "Person Surfing", []string{"surf", "surfing", "beach", "wave", "ocean"}},
		{"🏊", "Person Swimming", []string{"swim", "swimming", "pool", "water"}},
		{"🚴", "Person Biking", []string{"bike", "bicycle", "cycling", "sport"}},
		{"🧘", "Person in Lotus Position", []string{"yoga", "meditation", "zen", "mindfulness", "calm"}},
		{"🎮", "Video Game", []string{"game", "gaming", "video game", "controller", "play"}},
		{"🕹️", "Joystick", []string{"game", "arcade", "joystick", "retro"}},
		{"🎲", "Game Die", []string{"dice", "game", "random", "chance", "gambling"}},
		{"🧩", "Puzzle Piece", []string{"puzzle", "game", "piece", "jigsaw"}},
		{"♟️", "Chess Pawn", []string{"chess", "game", "strategy", "pawn"}},
		{"🎯", "Direct Hit", []string{"target", "bullseye", "goal", "aim", "dart"}},
		{"🎳", "Bowling", []string{"bowling", "sport", "pins", "ball"}},
		{"🎰", "Slot Machine", []string{"slot", "casino", "gambling", "jackpot"}},

		// Travel & Places
		{"🚗", "Automobile", []string{"car", "vehicle", "drive", "road", "auto"}},
		{"🚕", "Taxi", []string{"taxi", "cab", "car", "uber", "lyft"}},
		{"🚌", "Bus", []string{"bus", "vehicle", "public transport", "school"}},
		{"🚎", "Trolleybus", []string{"trolley", "bus", "tram", "transport"}},
		{"🏎️", "Racing Car", []string{"race car", "fast", "formula 1", "speed"}},
		{"🚓", "Police Car", []string{"police", "cop", "car", "emergency"}},
		{"🚑", "Ambulance", []string{"ambulance", "emergency", "hospital", "medical"}},
		{"🚒", "Fire Engine", []string{"fire truck", "fire", "emergency", "firefighter"}},
		{"🚲", "Bicycle", []string{"bike", "bicycle", "cycling", "pedal"}},
		{"🛵", "Motor Scooter", []string{"scooter", "moped", "vespa"}},
		{"🏍️", "Motorcycle", []string{"motorcycle", "bike", "harley"}},
		{"✈️", "Airplane", []string{"plane", "airplane", "flight", "travel", "fly"}},
		{"🚀", "Rocket", []string{"rocket", "space", "launch", "fast", "startup"}},
		{"🛸", "Flying Saucer", []string{"ufo", "alien", "space", "flying saucer"}},
		{"🚁", "Helicopter", []string{"helicopter", "chopper", "fly"}},
		{"🛶", "Canoe", []string{"canoe", "kayak", "boat", "paddle"}},
		{"⛵", "Sailboat", []string{"sailboat", "boat", "sailing", "yacht"}},
		{"🚢", "Ship", []string{"ship", "boat", "cruise", "ocean"}},
		{"🚂", "Locomotive", []string{"train", "locomotive", "steam", "railroad"}},
		{"🚆", "Train", []string{"train", "rail", "transport"}},
		{"🚇", "Metro", []string{"metro", "subway", "underground", "train"}},
		{"🏠", "House", []string{"house", "home", "building", "residence"}},
		{"🏡", "House with Garden", []string{"house", "home", "garden", "yard"}},
		{"🏢", "Office Building", []string{"office", "building", "work", "business"}},
		{"🏣", "Japanese Post Office", []string{"post office", "mail", "japan"}},
		{"🏥", "Hospital", []string{"hospital", "medical", "health", "doctor"}},
		{"🏦", "Bank", []string{"bank", "money", "finance", "building"}},
		{"🏨", "Hotel", []string{"hotel", "travel", "accommodation", "vacation"}},
		{"🏪", "Convenience Store", []string{"store", "shop", "convenience", "7-eleven"}},
		{"🏫", "School", []string{"school", "education", "building", "learn"}},
		{"🏛️", "Classical Building", []string{"museum", "government", "classical", "building"}},
		{"⛪", "Church", []string{"church", "religion", "christian", "building"}},
		{"🕌", "Mosque", []string{"mosque", "muslim", "islam", "religion"}},
		{"🕍", "Synagogue", []string{"synagogue", "jewish", "judaism", "religion"}},
		{"🗽", "Statue of Liberty", []string{"statue of liberty", "new york", "america", "freedom"}},
		{"🗼", "Tokyo Tower", []string{"tokyo tower", "japan", "landmark"}},
		{"🗾", "Map of Japan", []string{"japan", "map", "country"}},
		{"🌍", "Globe Europe-Africa", []string{"earth", "globe", "world", "europe", "africa"}},
		{"🌎", "Globe Americas", []string{"earth", "globe", "world", "america", "americas"}},
		{"🌏", "Globe Asia-Australia", []string{"earth", "globe", "world", "asia", "australia"}},

		// Tech & Objects
		{"💻", "Laptop", []string{"laptop", "computer", "work", "coding", "programming"}},
		{"🖥️", "Desktop Computer", []string{"desktop", "computer", "pc", "monitor"}},
		{"🖨️", "Printer", []string{"printer", "print", "paper", "office"}},
		{"⌨️", "Keyboard", []string{"keyboard", "type", "computer", "input"}},
		{"🖱️", "Computer Mouse", []string{"mouse", "computer", "click", "cursor"}},
		{"💾", "Floppy Disk", []string{"floppy", "disk", "save", "retro", "storage"}},
		{"💿", "Optical Disk", []string{"cd", "dvd", "disk", "disc", "music"}},
		{"📱", "Mobile Phone", []string{"phone", "mobile", "smartphone", "iphone", "android", "cell"}},
		{"☎️", "Telephone", []string{"phone", "telephone", "call", "retro"}},
		{"📞", "Telephone Receiver", []string{"phone", "call", "receiver"}},
		{"📺", "Television", []string{"tv", "television", "screen", "watch"}},
		{"📻", "Radio", []string{"radio", "music", "broadcast"}},
		{"🎙️", "Studio Microphone", []string{"microphone", "podcast", "recording", "studio"}},
		{"🎚️", "Level Slider", []string{"slider", "volume", "audio", "control"}},
		{"🎛️", "Control Knobs", []string{"knobs", "control", "audio", "mixer"}},
		{"🎤", "Microphone", []string{"microphone", "karaoke", "sing", "music"}},
		{"🎧", "Headphone", []string{"headphones", "music", "audio", "listen"}},
		{"📷", "Camera", []string{"camera", "photo", "picture", "photography"}},
		{"📹", "Video Camera", []string{"video", "camera", "record", "film"}},
		{"🎬", "Clapper Board", []string{"movie", "film", "action", "cinema", "director"}},
		{"📡", "Satellite Antenna", []string{"satellite", "antenna", "signal", "broadcast"}},
		{"🔋", "Battery", []string{"battery", "power", "energy", "charge"}},
		{"🔌", "Electric Plug", []string{"plug", "electric", "power", "outlet"}},
		{"💡", "Light Bulb", []string{"idea", "light", "bulb", "bright", "thought", "innovation"}},
		{"🔦", "Flashlight", []string{"flashlight", "light", "torch", "dark"}},
		{"🔒", "Locked", []string{"lock", "locked", "security", "private", "password"}},
		{"🔓", "Unlocked", []string{"unlock", "open", "security", "access"}},
		{"🔑", "Key", []string{"key", "lock", "unlock", "access", "password"}},
		{"🗝️", "Old Key", []string{"key", "old", "vintage", "antique"}},
		{"🔨", "Hammer", []string{"hammer", "tool", "build", "construction"}},
		{"🪓", "Axe", []string{"axe", "tool", "chop", "wood"}},
		{"⛏️", "Pick", []string{"pick", "pickaxe", "mine", "minecraft", "tool"}},
		{"🔧", "Wrench", []string{"wrench", "tool", "fix", "repair", "settings"}},
		{"🔩", "Nut and Bolt", []string{"nut", "bolt", "screw", "hardware"}},
		{"⚙️", "Gear", []string{"gear", "settings", "cog", "mechanical", "options"}},
		{"🧲", "Magnet", []string{"magnet", "attract", "magnetic"}},
		{"💈", "Barber Pole", []string{"barber", "haircut", "salon"}},
		{"🧪", "Test Tube", []string{"test tube", "science", "chemistry", "lab", "experiment"}},
		{"🧫", "Petri Dish", []string{"petri dish", "science", "biology", "lab"}},
		{"🧬", "DNA", []string{"dna", "genetics", "science", "biology", "helix"}},
		{"🔬", "Microscope", []string{"microscope", "science", "research", "lab", "biology"}},
		{"🔭", "Telescope", []string{"telescope", "astronomy", "space", "stars", "science"}},
		{"💉", "Syringe", []string{"syringe", "needle", "vaccine", "injection", "medical"}},
		{"💊", "Pill", []string{"pill", "medicine", "drug", "medication", "pharmacy"}},
		{"🩺", "Stethoscope", []string{"stethoscope", "doctor", "medical", "health"}},
		{"🩹", "Adhesive Bandage", []string{"bandage", "band-aid", "injury", "hurt", "heal"}},

		// Symbols
		{"❌", "Cross Mark", []string{"no", "wrong", "error", "cancel", "delete", "x"}},
		{"✅", "Check Mark Button", []string{"yes", "correct", "done", "complete", "success", "check"}},
		{"☑️", "Check Box with Check", []string{"check", "done", "complete", "checkbox"}},
		{"✔️", "Check Mark", []string{"check", "correct", "yes", "done", "approved"}},
		{"❓", "Question Mark", []string{"question", "what", "help", "confused"}},
		{"❗", "Exclamation Mark", []string{"exclamation", "important", "warning", "alert"}},
		{"‼️", "Double Exclamation Mark", []string{"exclamation", "important", "urgent", "emphasis"}},
		{"⁉️", "Exclamation Question Mark", []string{"surprise", "what", "shocked", "interrobang"}},
		{"💯", "Hundred Points", []string{"100", "perfect", "score", "hundred", "full marks"}},
		{"🔴", "Red Circle", []string{"red", "circle", "dot", "stop", "record"}},
		{"🟠", "Orange Circle", []string{"orange", "circle", "dot"}},
		{"🟡", "Yellow Circle", []string{"yellow", "circle", "dot"}},
		{"🟢", "Green Circle", []string{"green", "circle", "dot", "go", "online"}},
		{"🔵", "Blue Circle", []string{"blue", "circle", "dot"}},
		{"🟣", "Purple Circle", []string{"purple", "circle", "dot"}},
		{"⚫", "Black Circle", []string{"black", "circle", "dot"}},
		{"⚪", "White Circle", []string{"white", "circle", "dot"}},
		{"🔺", "Red Triangle Pointed Up", []string{"triangle", "up", "red", "arrow"}},
		{"🔻", "Red Triangle Pointed Down", []string{"triangle", "down", "red", "arrow"}},
		{"🔶", "Large Orange Diamond", []string{"orange", "diamond", "shape"}},
		{"🔷", "Large Blue Diamond", []string{"blue", "diamond", "shape"}},
		{"➕", "Plus", []string{"plus", "add", "positive", "more"}},
		{"➖", "Minus", []string{"minus", "subtract", "negative", "less"}},
		{"➗", "Divide", []string{"divide", "division", "math"}},
		{"✖️", "Multiply", []string{"multiply", "times", "x", "math"}},
		{"♾️", "Infinity", []string{"infinity", "forever", "endless", "unlimited"}},
		{"💲", "Heavy Dollar Sign", []string{"dollar", "money", "price", "cost", "currency"}},
		{"💱", "Currency Exchange", []string{"currency", "exchange", "money", "forex"}},
		{"©️", "Copyright", []string{"copyright", "legal", "c"}},
		{"®️", "Registered", []string{"registered", "trademark", "legal", "r"}},
		{"™️", "Trade Mark", []string{"trademark", "tm", "brand", "legal"}},
		{"🔙", "Back Arrow", []string{"back", "arrow", "return", "previous"}},
		{"🔚", "End Arrow", []string{"end", "arrow", "finish"}},
		{"🔛", "On! Arrow", []string{"on", "arrow", "enable"}},
		{"🔜", "Soon Arrow", []string{"soon", "arrow", "coming"}},
		{"🔝", "Top Arrow", []string{"top", "arrow", "up", "best"}},
		{"⬆️", "Up Arrow", []string{"up", "arrow", "north"}},
		{"⬇️", "Down Arrow", []string{"down", "arrow", "south"}},
		{"⬅️", "Left Arrow", []string{"left", "arrow", "west", "back"}},
		{"➡️", "Right Arrow", []string{"right", "arrow", "east", "forward", "next"}},
		{"↗️", "Up-Right Arrow", []string{"up right", "arrow", "northeast"}},
		{"↘️", "Down-Right Arrow", []string{"down right", "arrow", "southeast"}},
		{"↙️", "Down-Left Arrow", []string{"down left", "arrow", "southwest"}},
		{"↖️", "Up-Left Arrow", []string{"up left", "arrow", "northwest"}},
		{"↕️", "Up-Down Arrow", []string{"up down", "arrow", "vertical"}},
		{"↔️", "Left-Right Arrow", []string{"left right", "arrow", "horizontal"}},
		{"🔄", "Counterclockwise Arrows", []string{"refresh", "reload", "repeat", "sync", "update"}},
		{"🔃", "Clockwise Arrows", []string{"clockwise", "repeat", "cycle"}},
		{"🔁", "Repeat Button", []string{"repeat", "loop", "replay"}},
		{"🔂", "Repeat Single Button", []string{"repeat one", "loop", "single"}},
		{"▶️", "Play Button", []string{"play", "start", "video", "music"}},
		{"⏸️", "Pause Button", []string{"pause", "stop", "wait"}},
		{"⏹️", "Stop Button", []string{"stop", "end", "halt"}},
		{"⏺️", "Record Button", []string{"record", "recording", "red dot"}},
		{"⏭️", "Next Track Button", []string{"next", "skip", "forward"}},
		{"⏮️", "Last Track Button", []string{"previous", "back", "rewind"}},
		{"⏩", "Fast-Forward Button", []string{"fast forward", "skip", "speed"}},
		{"⏪", "Fast Reverse Button", []string{"rewind", "back", "reverse"}},
		{"🔀", "Shuffle Tracks Button", []string{"shuffle", "random", "mix"}},
		{"🔊", "Speaker High Volume", []string{"volume", "loud", "speaker", "sound"}},
		{"🔉", "Speaker Medium Volume", []string{"volume", "medium", "speaker", "sound"}},
		{"🔈", "Speaker Low Volume", []string{"volume", "low", "speaker", "quiet"}},
		{"🔇", "Muted Speaker", []string{"mute", "silent", "no sound", "quiet"}},
		{"🔔", "Bell", []string{"bell", "notification", "alert", "ring"}},
		{"🔕", "Bell with Slash", []string{"mute", "silent", "no notification", "quiet"}},
		{"📢", "Loudspeaker", []string{"announcement", "megaphone", "loud", "speaker"}},
		{"📣", "Megaphone", []string{"megaphone", "cheer", "announcement", "loud"}},

		// Office & Stationery
		{"📄", "Page Facing Up", []string{"document", "page", "file", "paper"}},
		{"📃", "Page with Curl", []string{"document", "page", "paper", "scroll"}},
		{"📝", "Memo", []string{"memo", "note", "write", "document", "edit", "pencil"}},
		{"📁", "File Folder", []string{"folder", "directory", "file", "organize"}},
		{"📂", "Open File Folder", []string{"folder", "open", "directory", "file"}},
		{"🗂️", "Card Index Dividers", []string{"dividers", "organize", "tabs", "index"}},
		{"📅", "Calendar", []string{"calendar", "date", "schedule", "event"}},
		{"📆", "Tear-Off Calendar", []string{"calendar", "date", "schedule"}},
		{"📇", "Card Index", []string{"rolodex", "contacts", "index", "cards"}},
		{"📈", "Chart Increasing", []string{"chart", "graph", "growth", "up", "stonks", "increase", "profit"}},
		{"📉", "Chart Decreasing", []string{"chart", "graph", "decline", "down", "decrease", "loss"}},
		{"📊", "Bar Chart", []string{"chart", "graph", "statistics", "data", "analytics"}},
		{"📋", "Clipboard", []string{"clipboard", "paste", "list", "tasks"}},
		{"📌", "Pushpin", []string{"pin", "pushpin", "location", "mark", "important"}},
		{"📍", "Round Pushpin", []string{"pin", "location", "map", "marker"}},
		{"📎", "Paperclip", []string{"paperclip", "attachment", "attach", "clip"}},
		{"🖇️", "Linked Paperclips", []string{"paperclips", "linked", "attachment"}},
		{"📏", "Straight Ruler", []string{"ruler", "measure", "length", "straight"}},
		{"📐", "Triangular Ruler", []string{"ruler", "triangle", "measure", "angle"}},
		{"✂️", "Scissors", []string{"scissors", "cut", "trim"}},
		{"🗃️", "Card File Box", []string{"file", "box", "storage", "archive"}},
		{"🗄️", "File Cabinet", []string{"cabinet", "file", "storage", "office"}},
		{"🗑️", "Wastebasket", []string{"trash", "delete", "garbage", "bin", "waste"}},
		{"✏️", "Pencil", []string{"pencil", "write", "edit", "draw"}},
		{"🖊️", "Pen", []string{"pen", "write", "sign"}},
		{"🖋️", "Fountain Pen", []string{"fountain pen", "write", "fancy"}},
		{"✒️", "Black Nib", []string{"pen", "nib", "write", "calligraphy"}},
		{"🖌️", "Paintbrush", []string{"paintbrush", "art", "paint", "draw"}},
		{"🖍️", "Crayon", []string{"crayon", "color", "draw", "kids"}},
		{"📚", "Books", []string{"books", "read", "study", "library", "education"}},
		{"📖", "Open Book", []string{"book", "read", "open", "study"}},
		{"📕", "Closed Book", []string{"book", "closed", "red"}},
		{"📗", "Green Book", []string{"book", "green"}},
		{"📘", "Blue Book", []string{"book", "blue"}},
		{"📙", "Orange Book", []string{"book", "orange"}},
		{"📓", "Notebook", []string{"notebook", "journal", "write"}},
		{"📔", "Notebook with Decorative Cover", []string{"notebook", "journal", "diary"}},
		{"📒", "Ledger", []string{"ledger", "notebook", "accounts"}},
		{"📰", "Newspaper", []string{"newspaper", "news", "press", "media"}},
		{"🗞️", "Rolled-Up Newspaper", []string{"newspaper", "news", "rolled"}},
		{"🏷️", "Label", []string{"label", "tag", "price", "sale"}},
		{"✉️", "Envelope", []string{"envelope", "email", "mail", "letter"}},
		{"📧", "E-Mail", []string{"email", "mail", "message", "inbox"}},
		{"📨", "Incoming Envelope", []string{"email", "incoming", "receive", "mail"}},
		{"📩", "Envelope with Arrow", []string{"email", "send", "outgoing", "mail"}},
		{"📤", "Outbox Tray", []string{"outbox", "send", "upload", "mail"}},
		{"📥", "Inbox Tray", []string{"inbox", "receive", "download", "mail"}},
		{"📦", "Package", []string{"package", "box", "delivery", "shipping", "parcel"}},
		{"📫", "Closed Mailbox with Raised Flag", []string{"mailbox", "mail", "inbox"}},
		{"📬", "Open Mailbox with Raised Flag", []string{"mailbox", "mail", "inbox"}},
		{"📭", "Open Mailbox with Lowered Flag", []string{"mailbox", "empty", "no mail"}},
		{"📮", "Postbox", []string{"postbox", "mail", "send", "letter"}},

		// Time
		{"⏰", "Alarm Clock", []string{"alarm", "clock", "time", "wake up", "morning"}},
		{"⏱️", "Stopwatch", []string{"stopwatch", "timer", "time", "speed"}},
		{"⏲️", "Timer Clock", []string{"timer", "clock", "countdown", "time"}},
		{"🕐", "One O'Clock", []string{"1", "one", "clock", "time"}},
		{"🕑", "Two O'Clock", []string{"2", "two", "clock", "time"}},
		{"🕒", "Three O'Clock", []string{"3", "three", "clock", "time"}},
		{"🕓", "Four O'Clock", []string{"4", "four", "clock", "time"}},
		{"🕔", "Five O'Clock", []string{"5", "five", "clock", "time"}},
		{"🕕", "Six O'Clock", []string{"6", "six", "clock", "time"}},
		{"🕖", "Seven O'Clock", []string{"7", "seven", "clock", "time"}},
		{"🕗", "Eight O'Clock", []string{"8", "eight", "clock", "time"}},
		{"🕘", "Nine O'Clock", []string{"9", "nine", "clock", "time"}},
		{"🕙", "Ten O'Clock", []string{"10", "ten", "clock", "time"}},
		{"🕚", "Eleven O'Clock", []string{"11", "eleven", "clock", "time"}},
		{"🕛", "Twelve O'Clock", []string{"12", "twelve", "clock", "time", "noon", "midnight"}},
		{"⌛", "Hourglass Done", []string{"hourglass", "time", "wait", "done"}},
		{"⏳", "Hourglass Not Done", []string{"hourglass", "time", "wait", "loading", "pending"}},

		// Misc
		{"🎵", "Musical Note", []string{"music", "note", "song", "melody", "sound"}},
		{"🎶", "Musical Notes", []string{"music", "notes", "song", "melody", "singing"}},
		{"🎼", "Musical Score", []string{"music", "score", "sheet music", "notes"}},
		{"🎹", "Musical Keyboard", []string{"piano", "keyboard", "music", "keys"}},
		{"🎸", "Guitar", []string{"guitar", "music", "rock", "instrument"}},
		{"🎺", "Trumpet", []string{"trumpet", "music", "brass", "instrument"}},
		{"🎻", "Violin", []string{"violin", "music", "classical", "instrument"}},
		{"🥁", "Drum", []string{"drum", "music", "percussion", "instrument"}},
		{"🎷", "Saxophone", []string{"saxophone", "music", "jazz", "instrument"}},
		{"🪕", "Banjo", []string{"banjo", "music", "country", "instrument"}},
		{"🎨", "Artist Palette", []string{"art", "paint", "palette", "creative", "design"}},
		{"🎭", "Performing Arts", []string{"theater", "drama", "masks", "acting", "performance"}},
		{"🎪", "Circus Tent", []string{"circus", "tent", "carnival", "fair"}},
		{"🎟️", "Admission Tickets", []string{"ticket", "admission", "event", "movie"}},
		{"🎫", "Ticket", []string{"ticket", "event", "admission", "pass"}},
		{"🧸", "Teddy Bear", []string{"teddy", "bear", "toy", "cute", "stuffed"}},
		{"🪀", "Yo-Yo", []string{"yo-yo", "toy", "play", "string"}},
		{"🪁", "Kite", []string{"kite", "fly", "wind", "toy"}},
		{"🔮", "Crystal Ball", []string{"crystal ball", "fortune", "magic", "future", "predict"}},
		{"🧿", "Nazar Amulet", []string{"evil eye", "amulet", "protection", "luck"}},
		{"🪄", "Magic Wand", []string{"magic", "wand", "wizard", "spell"}},
		{"🧙", "Mage", []string{"wizard", "mage", "magic", "fantasy"}},
		{"🧚", "Fairy", []string{"fairy", "magic", "fantasy", "wings"}},
		{"🧜", "Merperson", []string{"mermaid", "merman", "ocean", "sea", "fantasy"}},
		{"🧝", "Elf", []string{"elf", "fantasy", "magic", "tolkien"}},
		{"🧞", "Genie", []string{"genie", "wish", "lamp", "magic"}},
		{"🧟", "Zombie", []string{"zombie", "undead", "horror", "halloween"}},
		{"🦸", "Superhero", []string{"superhero", "hero", "power", "cape"}},
		{"🦹", "Supervillain", []string{"villain", "evil", "bad", "supervillain"}},
		{"🤴", "Prince", []string{"prince", "royal", "king", "crown"}},
		{"👸", "Princess", []string{"princess", "royal", "queen", "crown", "tiara"}},
		{"👰", "Person with Veil", []string{"bride", "wedding", "marriage", "veil"}},
		{"🤵", "Person in Tuxedo", []string{"groom", "wedding", "tuxedo", "formal"}},
		{"👼", "Baby Angel", []string{"angel", "baby", "cherub", "innocent"}},
		{"🎅", "Santa Claus", []string{"santa", "christmas", "xmas", "holiday"}},
		{"🤶", "Mrs. Claus", []string{"mrs claus", "christmas", "xmas", "holiday"}},
		{"🧑‍🎄", "Mx Claus", []string{"mx claus", "christmas", "xmas", "holiday"}},
		{"💀", "Skull", []string{"skull", "death", "dead", "skeleton", "halloween"}},
		{"👁️‍🗨️", "Eye in Speech Bubble", []string{"witness", "eye", "speech", "awareness"}},
		{"🗣️", "Speaking Head", []string{"speaking", "talk", "voice", "speech"}},
		{"👤", "Bust in Silhouette", []string{"person", "user", "profile", "silhouette", "account"}},
		{"👥", "Busts in Silhouette", []string{"people", "users", "group", "team", "profiles"}},
		{"🫂", "People Hugging", []string{"hug", "embrace", "comfort", "support", "friends"}},
		{"👣", "Footprints", []string{"footprints", "feet", "walk", "steps", "tracks"}},
		{"🐾", "Paw Prints", []string{"paw", "pet", "dog", "cat", "animal", "tracks"}},

		// Flags
		{"🏁", "Chequered Flag", []string{"finish", "race", "checkered", "flag", "end"}},
		{"🚩", "Triangular Flag", []string{"flag", "red flag", "warning", "marker"}},
		{"🎌", "Crossed Flags", []string{"flags", "japan", "celebration"}},
		{"🏴", "Black Flag", []string{"flag", "black", "pirate"}},
		{"🏳️", "White Flag", []string{"flag", "white", "surrender", "peace"}},
		{"🏳️‍🌈", "Rainbow Flag", []string{"pride", "lgbtq", "rainbow", "gay", "flag"}},
		{"🏳️‍⚧️", "Transgender Flag", []string{"transgender", "trans", "pride", "flag"}},
		{"🏴‍☠️", "Pirate Flag", []string{"pirate", "skull", "jolly roger", "flag"}},

		// Additional common emojis
		{"💬", "Speech Balloon", []string{"speech", "chat", "talk", "message", "comment", "bubble"}},
		{"💭", "Thought Balloon", []string{"thought", "think", "bubble", "idea"}},
		{"🗯️", "Right Anger Bubble", []string{"anger", "angry", "speech", "yell"}},
		{"💤", "Zzz", []string{"sleep", "zzz", "tired", "snore", "nap"}},
		{"💢", "Anger Symbol", []string{"anger", "angry", "mad", "frustration"}},
		{"💥", "Collision", []string{"boom", "explosion", "collision", "crash", "bang"}},
		{"💦", "Sweat Droplets", []string{"sweat", "water", "splash", "effort", "work"}},
		{"💨", "Dashing Away", []string{"dash", "fast", "run", "wind", "speed", "whoosh"}},
		{"🕳️", "Hole", []string{"hole", "empty", "void", "pit"}},
		{"👁️", "Eye", []string{"eye", "see", "look", "watch"}},
		{"👨‍💻", "Man Technologist", []string{"developer", "programmer", "coder", "tech", "man", "software"}},
		{"👩‍💻", "Woman Technologist", []string{"developer", "programmer", "coder", "tech", "woman", "software"}},
		{"🧑‍💻", "Technologist", []string{"developer", "programmer", "coder", "tech", "software", "engineer"}},
		{"👨‍🔬", "Man Scientist", []string{"scientist", "research", "lab", "man", "science"}},
		{"👩‍🔬", "Woman Scientist", []string{"scientist", "research", "lab", "woman", "science"}},
		{"👨‍🎨", "Man Artist", []string{"artist", "painter", "creative", "man", "art"}},
		{"👩‍🎨", "Woman Artist", []string{"artist", "painter", "creative", "woman", "art"}},
		{"👨‍🚀", "Man Astronaut", []string{"astronaut", "space", "nasa", "man", "rocket"}},
		{"👩‍🚀", "Woman Astronaut", []string{"astronaut", "space", "nasa", "woman", "rocket"}},
		{"👨‍🍳", "Man Cook", []string{"chef", "cook", "food", "man", "kitchen"}},
		{"👩‍🍳", "Woman Cook", []string{"chef", "cook", "food", "woman", "kitchen"}},
		{"🧑‍🍳", "Cook", []string{"chef", "cook", "food", "kitchen"}},
		{"👨‍⚕️", "Man Health Worker", []string{"doctor", "nurse", "medical", "man", "health"}},
		{"👩‍⚕️", "Woman Health Worker", []string{"doctor", "nurse", "medical", "woman", "health"}},
		{"👨‍🏫", "Man Teacher", []string{"teacher", "professor", "education", "man", "school"}},
		{"👩‍🏫", "Woman Teacher", []string{"teacher", "professor", "education", "woman", "school"}},
		{"👨‍🎓", "Man Student", []string{"student", "graduate", "education", "man", "school"}},
		{"👩‍🎓", "Woman Student", []string{"student", "graduate", "education", "woman", "school"}},
		{"🧑‍🎓", "Student", []string{"student", "graduate", "education", "school"}},
	}
}
